window.WFC_STRINGS = {
  "en": {
    "site.name": "Wise Financial Cambodia",
    "site.tagline": "Financial Education Tools",
    "site.footer.main": "Wise Financial Cambodia — Financial Education for the Kingdom of Cambodia",
    "site.footer.edu": "Calculators are for educational purposes. Consult a financial advisor for personal advice.",
    "site.footer.edu_short": "Calculators are for educational purposes only.",
    "nav.all": "All Calculators",
    "nav.savings": "Savings",
    "nav.loans": "Loans",
    "nav.budgeting": "Budgeting",
    "nav.fixed": "Fixed Savings",
    "nav.monthly": "Monthly Savings",
    "nav.loan": "Loan Calculator",
    "bread.calculators": "Calculators",
    "bread.savings": "Savings",
    "bread.loans": "Loans",
    "index.title": "Financial Calculators",
    "index.desc": "Free, easy-to-use tools to help you plan your savings, understand loans, and make wise financial decisions. All calculations happen right in your browser.",
    "index.savings_col": "💰 Savings Calculators",
    "index.loans_col": "🏦 Loan Calculators",
    "index.budget_col": "📊 Budgeting Calculators",
    "badge.live": "Live",
    "badge.soon": "Soon",
    "calc.fixed.name": "Fixed Deposit Savings",
    "calc.fixed.desc": "Grow a lump-sum deposit at compound interest over time",
    "calc.monthly.name": "Monthly Contribution Savings",
    "calc.monthly.desc": "See how regular monthly deposits build up your balance",
    "calc.emergency.name": "Emergency Fund",
    "calc.emergency.desc": "Estimate how much to save for emergencies based on your expenses",
    "calc.nssf.name": "NSSF Pension",
    "calc.nssf.desc": "Approximate your future balance with Cambodia’s NSSF program",
    "calc.retire.name": "Retirement Future Balance",
    "calc.retire.desc": "Calculate future balance of your personal retirement plan",
    "ret.page_title": "Retirement Plan",
    "ret.bread": "Retirement Plan",
    "ret.print_title": "Retirement Plan",
    "ret.page_desc": "Two questions in one place: how much will you have saved by the time you retire, and will it last for the rest of your life?",
    "ret.card.saving": "While You Are Still Working",
    "ret.card.spending": "After You Retire",
    "ret.input.current_age": "Your Age Now",
    "ret.input.retire_age": "Age You Want to Retire",
    "ret.input.current_savings": "Money You Have Saved Already",
    "ret.input.monthly_saving": "Amount You Save Each Month",
    "ret.input.save_return": "Interest Rate While Saving",
    "ret.input.life_expectancy": "Plan Until Age",
    "ret.input.monthly_spend": "Money You Need Each Month",
    "ret.input.inflation": "Prices Go Up By",
    "ret.input.spend_return": "Interest Rate After Retiring",
    "ret.input.fd1_amount": "Deposit 1 Amount",
    "ret.input.fd1_rate": "Deposit 1 Interest Rate",
    "ret.input.fd2_amount": "Deposit 2 Amount",
    "ret.input.fd2_rate": "Deposit 2 Interest Rate",
    "ret.input.easy_rate": "Rate After Breaking a Deposit",
    "ret.unit.years": "years",
    "ret.unit.per_year": "% / yr",
    "ret.derived.balance": "Savings when you retire",
    "ret.hint.years_until": "That gives you {years} years to save.",
    "ret.hint.years_retired": "That is {years} years of retirement to pay for.",
    "ret.hint.inflation": "Your monthly spending grows at this rate, so later years cost more.",
    "ret.hint.fd_split": "Your retirement savings are split evenly between the two. Change the amounts if you plan differently.",
    "ret.hint.easy_rate": "If you take money out early, the bank usually drops you to an ordinary savings rate.",
    "ret.section.deposits": "Your Two Fixed Deposits",
    "ret.model.simple": "One Savings Pot",
    "ret.model.simple_sub": "All your money in one account",
    "ret.model.fd": "Two Fixed Deposits",
    "ret.model.fd_sub": "Live on the interest first",
    "ret.btn.resplit": "↺ Split evenly again",
    "ret.verdict.enough": "Your savings last",
    "ret.verdict.enough_sub": "Your money lasts to age {age}, with {amount} still left over.",
    "ret.verdict.short": "Your savings run out early",
    "ret.verdict.short_sub": "The money runs out at age {age} — {years} years short of your plan.",
    "ret.stat.balance": "Savings at Retirement",
    "ret.stat.balance_sub": "what you start retirement with",
    "ret.stat.contributed": "You Put In",
    "ret.stat.contributed_sub": "your own money",
    "ret.stat.interest": "Bank Interest",
    "ret.stat.interest_sub": "earned while saving",
    "ret.stat.withdrawn": "You Take Out",
    "ret.stat.withdrawn_sub": "across retirement",
    "ret.stat.left": "Left at the End",
    "ret.stat.left_ok": "money to pass on",
    "ret.stat.left_none": "nothing left",
    "ret.chart.title": "Your Money Over a Lifetime",
    "ret.chart.note": "The line rises while you are saving, then falls once you retire and start spending.",
    "ret.chart.series": "Savings Balance",
    "ret.chart.age": "Age",
    "ret.chart.balance": "Savings Balance",
    "ret.sched.title": "Year-by-Year Detail",
    "ret.sched.age": "Age",
    "ret.sched.phase": "Stage",
    "ret.sched.in_out": "Added / Taken",
    "ret.sched.interest": "Interest Earned",
    "ret.sched.balance": "Balance",
    "ret.sched.saving": "Saving",
    "ret.sched.retired": "Retired",
    "ret.sched.note_simple": "Amounts are totals for each year. Rows in red are years where the money had run out.",
    "ret.sched.note_fd": "Amounts are totals for each year. Rows in amber are after a deposit was broken and its rate dropped. Rows in red are years where the money had run out.",
    "ret.guide.title": "How This Works",
    "ret.guide.phase1": "<strong>While you are working</strong> — each month the bank adds interest to your balance, then you add your saving on top. Small amounts add up over many years.",
    "ret.guide.phase2": "<strong>After you retire</strong> — you stop adding money and start taking it out. Your spending grows every year because prices rise.",
    "ret.guide.simple": "<strong>One savings pot</strong> — all your money sits in one account earning interest, and you withdraw what you need each month.",
    "ret.guide.fd": "<strong>Two fixed deposits</strong> — you live on the interest for as long as it covers your spending. Only when it falls short do you break into the first deposit, and the bank then pays you a lower rate on it.",
    "ret.guide.warning": "⚠️ <strong>This is an estimate, not a promise.</strong> Interest rates and prices change. Review your plan every year rather than trusting one number.",
    "calc.homevsbank.name": "Savings: Home vs. Bank",
    "calc.homevsbank.desc": "Compare early and late savers keeping money at home vs. the bank",
    "calc.invest.name": "Investment Evaluation",
    "calc.invest.desc": "Assess whether an investment is giving a healthy return",
    "invest.page_title": "Investment Evaluation",
    "calc.simple_daily.name": "Simple Interest – Daily",
    "calc.simple_daily.desc": "Calculate daily loan interest; find unknown interest rate",
    "calc.simple_monthly.name": "Simple Interest – Monthly/Yearly",
    "calc.simple_monthly.desc": "Monthly or yearly simple interest; find unknown interest rate",
    "calc.loan4.name": "Loan Calculator (4 Parts)",
    "calc.loan4.desc": "Solve for any missing piece of a loan (principal, rate, term, payment)",
    "calc.compound_loan.name": "Compound Interest Loan",
    "calc.compound_loan.desc": "Full amortisation schedule with holiday-aware payment dates and overrides",
    "calc.loan_flexible.name": "Flexible Loan (Periodic Principal)",
    "calc.loan_flexible.desc": "Interest charged monthly, principal repaid in larger periodic lump sums",
    "calc.loan_multi_rate.name": "Compound Loan — Multiple Rates",
    "calc.loan_multi_rate.desc": "Loan with changing interest rate periods; includes late fee / overdue penalty calculator",
    "calc.loan_adjusted.name": "Loan Restructure Comparison",
    "calc.loan_adjusted.desc": "Side-by-side: current loan terms vs. proposed restructure — models underpayment and rate changes",
    "calc.loan_comp.name": "Loan Comparison",
    "calc.loan_comp.desc": "Equal payment vs. equal principal payment side-by-side",
    "calc.promo.name": "Promotional Loan",
    "calc.promo.desc": "Loans with different interest rate periods",
    "calc.cambodia_loans.name": "Comparing Cambodian Loans",
    "calc.cambodia_loans.desc": "Compare all common debt types available in Cambodia",
    "calc.loan_penalties.name": "Loan Penalties Calculator",
    "calc.loan_penalties.desc": "See how a late or partial payment splits between penalty, interest, and principal",
    "calc.credit_card.name": "Credit Card Debt",
    "calc.credit_card.desc": "Understand the true cost of credit card balances",
    "calc.debt_payoff.name": "Debt Pay-Off Strategies",
    "calc.debt_payoff.desc": "Find the best path to pay off multiple loans",
    "calc.dti.name": "DTI – Debt to Income Ratio",
    "calc.dti.desc": "Determine your ability to take on housing and other debt",
    "calc.rent_vs_buy.name": "Renting vs. Financing",
    "calc.rent_vs_buy.desc": "Is it more economical to rent or finance a home?",
    "calc.family_budget.name": "Family Budget",
    "calc.family_budget.desc": "Basic budget planning for a family",
    "calc.church_budget.name": "Church Budget",
    "calc.church_budget.desc": "Simple tool for making church budgets",
    "calc.farm_budget.name": "Farming Budget",
    "calc.farm_budget.desc": "Calculate whether a crop is profitable",
    "calc.insurance.name": "Insurance – End Early?",
    "calc.insurance.desc": "Evaluate whether cancelling an insurance policy is a good idea",
    "calc.inflation.name": "Cambodian Inflation Calculator",
    "calc.inflation.desc": "What is a fixed amount of money worth in today’s terms?",
    "input.label": "Inputs",
    "input.main": "Main Inputs",
    "input.optional": "Optional Settings",
    "input.annual_rate": "Annual Interest Rate",
    "input.time_period": "Time Period",
    "input.unit": "Unit",
    "input.years": "Years",
    "input.months": "Months",
    "input.comp_freq": "Compounding Frequency",
    "input.freq.monthly": "Monthly",
    "input.freq.quarterly": "Quarterly",
    "input.freq.semi": "Semi-Annual",
    "input.freq.annual": "Annual",
    "input.freq.daily": "Daily",
    "input.nationality": "Depositor Type",
    "input.nat.national": "Cambodian National (6% tax)",
    "input.nat.foreigner": "Foreigner (12% tax)",
    "input.days_unit": "days",
    "btn.calculate": "Calculate",
    "result.summary": "Summary Results",
    "result.effective_rate": "Effective Annual Yield",
    "result.rule72": "Years to Double (Rule of 72)",
    "result.quick_cmp": "Quick Comparison",
    "cmp.scenario": "Scenario",
    "cmp.future_value": "Future Value",
    "cmp.current": "▶ Current Plan",
    "cmp.plus1": "If rate were +1%",
    "cmp.minus1": "If rate were −1%",
    "cmp.double_time": "Double the time",
    "fixed.page_title": "Fixed Deposit Savings Calculator",
    "fixed.page_desc": "See how a one-time deposit grows with compound interest over time",
    "fixed.bread": "Fixed Deposit Savings Calculator",
    "fixed.print_title": "Fixed Deposit Savings Calculator",
    "fixed.input.principal": "Initial Deposit",
    "fixed.result.future_value_net": "After-Tax Future Value",
    "fixed.result.principal": "Initial Deposit",
    "fixed.result.gross_interest": "Gross Interest Earned",
    "fixed.result.tax_deducted": "Tax Deducted",
    "fixed.result.net_interest": "Net Interest (after tax)",
    "fixed.chart.title": "Savings Growth Chart",
    "fixed.chart.net_balance": "After-Tax Balance",
    "fixed.chart.gross_balance": "Gross Balance (before tax)",
    "fixed.chart.principal": "Principal",
    "cmp.fixed.half": "If deposit were half",
    "cmp.fixed.double": "If deposit were double",
    "simple_monthly.page_title": "Simple Interest – Monthly/Yearly Repayment Calculator",
    "simple_monthly.page_desc": "Calculate interest and repayment schedules for simple-interest loans. Choose whether interest is charged monthly or yearly, and whether it is based on the original or remaining balance. Optionally set a higher payment to start reducing the principal.",
    "simple_monthly.bread": "Simple Interest – Monthly/Yearly",
    "simple_monthly.print_title": "Simple Interest – Monthly/Yearly Repayment Calculator",
    "simple_monthly.card.payment": "Payment Settings",
    "simple_monthly.input.rate": "Interest Rate",
    "simple_monthly.input.rate_period": "Rate Period",
    "simple_monthly.input.period.monthly": "Per Month",
    "simple_monthly.input.period.yearly": "Per Year",
    "simple_monthly.input.interest_base": "Calculate Interest On",
    "simple_monthly.input.base.original": "Original Principal",
    "simple_monthly.input.base.remaining": "Remaining Balance",
    "simple_monthly.input.principal_label": "Principal Reduction (optional)",
    "simple_monthly.input.principal_hint": "Set a monthly payment above the interest amount to start paying off the principal.",
    "simple_monthly.input.new_payment": "Monthly Payment",
    "simple_monthly.input.new_payment_date": "Payment Start Date (optional)",
    "simple_monthly.result.total_repaid": "Total Amount Repaid",
    "simple_monthly.result.interest_only": "Monthly Interest Payment",
    "simple_monthly.result.never_paid": "No end date",
    "simple_monthly.result.never_paid_hint": "Loan is never paid off — set a payment above the interest to repay principal",
    "simple_monthly.result.total_interest": "Total Interest Paid",
    "simple_monthly.result.monthly_interest": "Monthly Interest",
    "simple_monthly.result.yearly_interest": "Annual Interest",
    "simple_monthly.result.term": "Loan Term",
    "simple_monthly.result.months": "months",
    "simple_monthly.result.partial": "partial",
    "simple_monthly.per_month": "/mo",
    "simple_monthly.per_year": "/yr",
    "simple_monthly.chart.title": "Remaining Balance Over Time",
    "simple_monthly.chart.balance": "Remaining Balance",
    "simple_monthly.sched.month": "Month",
    "simple_monthly.sched.interest": "Interest",
    "simple_monthly.sched.payment": "Payment",
    "simple_monthly.sched.principal_paid": "Principal Paid",
    "simple_monthly.sched.never_paid_note": "This pattern continues indefinitely. Set a monthly payment above the interest amount to pay off the loan.",
    "simple_daily.page_title": "Simple Interest Daily Repayment Calculator",
    "simple_daily.page_desc": "Enter the loan amount and total payback amount to see the daily payment schedule and true annual interest rate for up to three repayment term options.",
    "simple_daily.bread": "Simple Interest – Daily",
    "simple_daily.print_title": "Simple Interest Daily Repayment Calculator",
    "simple_daily.input.currency": "Currency",
    "simple_daily.input.loan": "Loan Amount (Principal)",
    "simple_daily.input.payback": "Payback Amount (Total to Repay)",
    "simple_daily.input.start_date": "Loan Start Date (optional)",
    "simple_daily.input.options_label": "Repayment Term Options",
    "simple_daily.input.opt1": "Option 1",
    "simple_daily.input.opt2": "Option 2",
    "simple_daily.input.opt3": "Option 3",
    "simple_daily.result.total_interest": "Total Interest (Lender Profit)",
    "simple_daily.result.loan_amount": "Loan Amount",
    "simple_daily.result.payback_amount": "Payback Amount",
    "simple_daily.result.comparison": "Option Comparison",
    "simple_daily.result.option_col": "Option",
    "simple_daily.result.days_col": "Days",
    "simple_daily.result.daily_pmt_col": "Daily Payment",
    "simple_daily.result.annual_rate_col": "Annual Rate",
    "simple_daily.chart.title": "Daily Remaining Balance",
    "simple_daily.chart.opt1": "Option 1",
    "simple_daily.chart.opt2": "Option 2",
    "simple_daily.chart.opt3": "Option 3",
    "simple_daily.sched.day": "Day",
    "simple_daily.sched.date": "Date",
    "monthly.page_title": "Monthly Contribution Savings Calculator",
    "monthly.page_desc": "See how regular monthly deposits — with or without an initial sum — grow over time",
    "monthly.bread": "Monthly Contribution Savings Calculator",
    "monthly.print_title": "Monthly Contribution Savings Calculator",
    "monthly.input.contrib": "Monthly Contribution",
    "monthly.input.principal": "Initial Deposit (optional)",
    "monthly.input.timing": "Contribution Timing",
    "monthly.timing.end": "End of Period",
    "monthly.timing.begin": "Beginning of Period",
    "monthly.result.future_value": "Future Value",
    "monthly.result.future_value_net": "After-Tax Future Value",
    "monthly.result.principal": "Initial Deposit",
    "monthly.result.total_contribs": "Total Contributions",
    "monthly.result.total_principal": "Total Principal Invested",
    "monthly.result.total_interest": "Total Interest Earned",
    "monthly.result.gross_interest": "Gross Interest Earned",
    "monthly.result.tax_deducted": "Tax Deducted",
    "monthly.result.net_interest": "Net Interest (after tax)",
    "monthly.chart.title": "Savings Growth Chart",
    "monthly.chart.balance": "After-Tax Balance",
    "monthly.chart.gross_balance": "Gross Balance (before tax)",
    "monthly.chart.invested": "Total Invested",
    "cmp.monthly.lump_only": "Lump sum only (no monthly)",
    "cmp.monthly.month_only": "Monthly only (no lump sum)",
    "loan.page_title": "Loan Calculator (4 Parts)",
    "loan.page_desc": "Know any 3 loan variables? Solve for the missing one — payment, principal, interest rate, or loan term.",
    "loan.bread": "Loan Calculator (4 Parts)",
    "loan.print_title": "Loan Calculator (4 Parts)",
    "loan.section.currency": "Currency",
    "loan.exrate": "Exchange Rate (1 USD =)",
    "loan.section.solve": "Solve For",
    "loan.solve.payment": "Monthly\nPayment",
    "loan.solve.principal": "Loan\nAmount",
    "loan.solve.rate": "Interest\nRate",
    "loan.solve.nper": "Loan\nTerm",
    "loan.section.details": "Loan Details",
    "loan.input.principal": "Loan Amount",
    "loan.input.rate": "Annual Interest Rate",
    "loan.input.term": "Loan Term",
    "loan.input.payment": "Monthly Payment",
    "loan.result.principal": "Loan Amount",
    "loan.result.payment": "Monthly Payment",
    "loan.result.total_paid": "Total Amount Paid",
    "loan.result.total_interest": "Total Interest Paid",
    "loan.result.interest_pct": "Interest as % of Principal",
    "loan.result.term": "Loan Term",
    "loan.hero.payment": "Monthly Payment",
    "loan.hero.principal": "Loan Amount",
    "loan.hero.rate": "Annual Interest Rate",
    "loan.hero.nper": "Loan Term",
    "loan.chart.title": "Loan Balance Over Time",
    "loan.chart.balance": "Remaining Balance",
    "loan.chart.cum_interest": "Cumulative Interest Paid",
    "loan.schedule.title": "Amortization Schedule",
    "loan.sched.payment_num": "Payment #",
    "loan.sched.payment": "Payment",
    "loan.sched.principal": "Principal",
    "loan.sched.remaining": "Remaining Balance",
    "cmp.loan.header.pmt": "Monthly Payment",
    "cmp.loan.header.int": "Total Interest",
    "cmp.loan.plus1": "Rate +1%",
    "cmp.loan.minus1": "Rate −1%",
    "cmp.loan.1yr": "1-year term",
    "cmp.loan.3yr": "3-year term",
    "schedule.title": "Period-by-Period Schedule",
    "schedule.show": "Show Schedule",
    "schedule.hide": "Hide Schedule",
    "sched.period": "Period",
    "sched.date": "Date",
    "sched.beg_balance": "Beg. Balance",
    "sched.interest": "Interest Earned",
    "sched.gross_interest": "Gross Interest",
    "sched.tax": "Tax",
    "sched.net_interest": "Net Interest",
    "sched.end_balance": "End Balance",
    "sched.cum_interest": "Cumulative Interest",
    "sched.cum_net_interest": "Cum. Net Interest",
    "sched.cum_contribs": "Cum. Contributions",
    "fl.page_title": "Flexible Loan — Periodic Principal",
    "fl.page_desc": "Interest is charged monthly on the outstanding balance. Principal is repaid in periodic lump sums every N months. Generates a full date-based amortisation schedule with holiday-aware payment dates.",
    "fl.bread": "Flexible Loan",
    "fl.print_title": "Flexible Loan Calculator",
    "fl.section.loan": "Loan Details",
    "fl.section.dates": "Dates",
    "fl.section.settings": "Settings",
    "fl.section.structure": "Payment Structure",
    "fl.input.loan_amount": "Loan Amount",
    "fl.input.rate": "Annual Interest Rate",
    "fl.input.term": "Loan Term",
    "fl.input.start_date": "Loan Start Date",
    "fl.input.override_date": "Override Start Date",
    "fl.input.override_hint": "Optional – overrides the reference date for the first period's day count only",
    "fl.input.first_payment": "First Payment Date",
    "fl.input.day_count": "Day Count Method",
    "fl.day_count.standard": "Standard – Actual days / 360",
    "fl.day_count.actual": "Actual – Actual days / 365",
    "fl.input.delay_rule": "Payment Date Rule",
    "fl.delay.none": "No adjustment",
    "fl.delay.skip_sun": "Skip Sunday",
    "fl.delay.skip_sat_sun": "Skip Saturday & Sunday",
    "fl.delay.skip_sun_hol": "Skip Sunday & Holidays",
    "fl.delay.skip_all": "Skip Sat, Sun & Holidays",
    "fl.input.frequency": "Principal Payment Frequency",
    "fl.input.frequency_unit": "months",
    "fl.input.freq_start": "Frequency Start Date",
    "fl.input.fixed_principal": "Fixed Principal / Payment",
    "fl.principal.auto": "auto",
    "fl.principal.reset": "reset to auto",
    "fl.input.defer": "Defer Interest to Payment",
    "fl.defer.no": "No – pay interest monthly",
    "fl.defer.yes": "Yes – accumulate, pay with principal",
    "fl.result.monthly_interest": "Typical Monthly Interest",
    "fl.result.lump_sum": "Principal Lump Sum",
    "fl.result.total_paid": "Total Amount Paid",
    "fl.result.total_principal": "Total Principal",
    "fl.result.total_interest": "Total Interest",
    "fl.result.maturity": "Maturity Date",
    "fl.chart.title": "Loan Balance Over Time",
    "fl.chart.balance": "Remaining Balance",
    "fl.chart.cum_interest": "Cumulative Interest",
    "fl.sched.title": "Amortisation Schedule",
    "fl.sched.num": "No.",
    "fl.sched.date": "Payment Date",
    "fl.sched.days": "Days",
    "fl.sched.principal": "Principal",
    "fl.sched.interest": "Interest",
    "fl.sched.total": "Total",
    "fl.sched.balance": "Balance",
    "fl.sched.totals": "Totals",
    "ef.page_title": "Emergency Fund Calculator",
    "ef.page_desc": "Enter your monthly expenses to find out how much you need in an emergency fund. Experts recommend saving 3-6 months of living expenses.",
    "ef.bread": "Emergency Fund",
    "ef.print_title": "Emergency Fund Calculator",
    "ef.section.expenses": "Monthly Expenses",
    "ef.col.amount": "Amount",
    "ef.input.housing": "Housing (Rent, Utilities)",
    "ef.input.food": "Food",
    "ef.input.transport": "Transportation",
    "ef.input.debt": "Debt Payments",
    "ef.input.education": "Child Education",
    "ef.input.phone": "Phone",
    "ef.input.insurance": "Insurance",
    "ef.input.property_tax": "Property Tax",
    "ef.input.other": "Other",
    "ef.total": "Total Monthly Expenses",
    "ef.goals.title": "Emergency Fund Goals",
    "ef.level.basic_dot": "Basic",
    "ef.level.good_dot": "Good",
    "ef.level.better_dot": "Better",
    "ef.level.basic_desc": "1 month of expenses",
    "ef.level.good_desc": "3 months of expenses",
    "ef.level.better_desc": "6 months of expenses",
    "ef.goal.basic": "1 Month - Basic",
    "ef.goal.basic_sub": "Minimum recommended",
    "ef.goal.good": "3 Months - Good",
    "ef.goal.good_sub": "Standard recommendation",
    "ef.goal.better": "6 Months - Better",
    "ef.goal.better_sub": "Best practice",
    "ef.chart.title": "Emergency Fund Goals",
    "cln.page_title": "Compound Interest Loan",
    "cln.page_desc": "Build a full date-based amortisation schedule for a compound interest loan. Choose 30/360 or Actual/360 day count, with automatic adjustment for Sundays and Cambodian public holidays.",
    "cln.bread": "Compound Interest Loan",
    "cln.print_title": "Compound Interest Loan Calculator",
    "cln.input.loan_amount": "Loan Amount",
    "cln.input.rate": "Annual Interest Rate",
    "cln.input.term": "Loan Term",
    "cln.input.start_date": "Loan Start Date",
    "cln.input.first_payment": "First Payment Date",
    "cln.input.day_count": "Day Count Method",
    "cln.day_count.30_360": "30/360 (rate ÷ 12 per period)",
    "cln.day_count.actual_360": "Actual/360 (rate ÷ 360 × actual days)",
    "cln.input.delay_rule": "Payment Date Rule",
    "cln.delay.none": "No adjustment",
    "cln.delay.skip_sun": "Skip Sunday → Monday",
    "cln.delay.skip_sun_hol": "Skip Sunday & Cambodian Holidays",
    "cln.delay.skip_sat_sun": "Skip Saturday & Sunday → Monday",
    "cln.delay.skip_sat_sun_hol": "Skip Sat, Sun & Cambodian Holidays",
    "cln.input.payment": "Monthly Payment",
    "cln.input.payment_auto": "auto",
    "cln.override_reset": "reset to auto",
    "cln.result.payment": "Monthly Payment",
    "cln.result.num_payments": "Number of Payments",
    "cln.result.total_paid": "Total Amount Paid",
    "cln.result.total_interest": "Total Interest Paid",
    "cln.result.total_principal": "Total Principal Paid",
    "cln.result.final_date": "Final Payment Date",
    "cln.hint.start_date": "Optional — defaults to today",
    "cln.hint.first_payment": "Optional — auto-set to 1 month after start",
    "lcp.page_title": "Loan Comparison Calculator",
    "lcp.page_desc": "Compare equal payment (standard amortisation) with equal principal repayment side by side. See which method costs less in total interest.",
    "lcp.bread": "Loan Comparison",
    "lcp.print_title": "Loan Comparison Calculator",
    "lcp.col.ep": "Equal Payment",
    "lcp.col.ep_desc": "Fixed amount every month",
    "lcp.col.epr": "Equal Principal",
    "lcp.col.epr_desc": "Same principal every month; payments decrease",
    "lcp.result.monthly_payment": "Monthly Payment",
    "lcp.result.first_payment": "First Payment",
    "lcp.result.last_payment": "Last Payment",
    "lcp.result.total_paid": "Total Amount Paid",
    "lcp.result.total_interest": "Total Interest Paid",
    "lcp.result.num_payments": "Number of Payments",
    "lcp.result.final_date": "Final Payment Date",
    "lcp.savings.saves": "saves",
    "lcp.savings.note_epr": "in total interest vs. Equal Payment",
    "lcp.savings.note_ep": "in total interest vs. Equal Principal",
    "lcp.chart.title": "Loan Balance Over Time",
    "lcp.chart.ep_balance": "Equal Payment — Balance",
    "lcp.chart.epr_balance": "Equal Principal — Balance",
    "lcp.chart.ep_principal": "Equal Payment — Principal",
    "lcp.chart.ep_interest": "Equal Payment — Interest",
    "lcp.chart.epr_principal": "Equal Principal — Principal",
    "lcp.chart.epr_interest": "Equal Principal — Interest",
    "lcp.chart.view_balance": "Balance",
    "lcp.chart.view_split": "Payment Split",
    "currency.khr_note": "Exchange rate: 4,000 KHR = 1 USD (fixed)",
    "cln.chart.title": "Loan Balance Over Time",
    "cln.chart.balance": "Remaining Balance",
    "cln.chart.cum_interest": "Cumulative Interest",
    "cln.sched.title": "Amortisation Schedule",
    "cln.sched.num": "Payment #",
    "cln.sched.date": "Date",
    "cln.sched.days": "Days",
    "cln.sched.principal": "Principal",
    "cln.sched.interest": "Interest",
    "cln.sched.payment": "Payment",
    "cln.sched.balance": "Balance",
    "cln.sched.totals": "Totals",
    "print.note": "Click <strong>Print / Save as PDF</strong> to export results. Use your browser’s print dialog and choose \"Save as PDF\" as the destination.",
    "print.btn": "Print / Save as PDF",
    "print.date_prefix": "printed",
    "cmr.page_title": "Compound Loan — Multiple Rates",
    "cmr.page_desc": "Build a full amortisation schedule for a loan with changing interest rate periods. Track actual payments and calculate overdue penalty fees.",
    "cmr.bread": "Compound Loan — Multiple Rates",
    "cmr.print_title": "Compound Loan — Multiple Rates Calculator",
    "cmr.section.periods": "Rate Periods",
    "cmr.period_label": "Period {n}",
    "cmr.input.penalty_rate": "Penalty Rate (Annual)",
    "cmr.hint.penalty_rate": "Applied to unpaid amounts in the overdue calculator below",
    "cmr.input.period_start": "Period Start Date",
    "cmr.hint.period_start": "First payment date of this rate period",
    "cmr.btn.add_period": "+ Add Rate Period",
    "cmr.btn.remove_period": "Remove",
    "cmr.error.period_date_required": "Period {n} start date is required.",
    "cmr.error.period_date_order": "Period start dates must be after the loan start date.",
    "cmr.error.first_date_order": "First payment date must be after the loan start date.",
    "cmr.sched.status": "Status",
    "cmr.sched.paid": "Paid",
    "cmr.sched.notes": "Notes",
    "cmr.status.paid_full": "Paid Full",
    "cmr.status.partial": "Partial Paid",
    "cmr.late.section": "Overdue Penalty Calculator",
    "cmr.late.desc": "Enter a date to see penalty fees on all unpaid or partially paid instalments.",
    "cmr.late.as_of": "Calculate As Of",
    "cmr.late.no_calc": "Enter an \"As Of\" date above to calculate overdue penalties.",
    "cmr.late.none": "No overdue payments found as of this date.",
    "cmr.late.num": "#",
    "cmr.late.date_col": "Due Date",
    "cmr.late.days_col": "Days Overdue",
    "cmr.late.installment": "Installment",
    "cmr.late.paid_col": "Paid",
    "cmr.late.unpaid_col": "Unpaid",
    "cmr.late.penalty_col": "Penalty",
    "cmr.late.total_col": "Total Overdue",
    "cmr.late.total_row": "Total",
    "cmr.late.remaining_loan": "Remaining Loan Balance",
    "cmr.late.total_penalty": "Total Penalty Added",
    "cmr.late.grand_total": "Grand Total Owing",
    "cinf.page_title": "Cambodian Inflation Calculator",
    "cinf.desc": "See how the purchasing power of money has changed over time in Cambodia using official CPI data from the National Institute of Statistics.",
    "cinf.section.inputs": "Inputs",
    "cinf.section.results": "Results",
    "cinf.input.amount": "Amount",
    "cinf.input.from_date": "From Month",
    "cinf.input.to_date": "To Month",
    "cinf.note.source_label": "Data source:",
    "cinf.note.source": "National Institute of Statistics (NIS), Cambodia. CPI base: Oct–Dec 2006 = 100.",
    "cinf.note.latest_label": "Latest data:",
    "cinf.placeholder": "Enter an amount and date range above.",
    "cinf.error.date_order": "\"From\" month must be before \"To\" month.",
    "cinf.result.hero_label": "Equivalent Purchasing Power",
    "cinf.result.total_change": "Total Inflation",
    "cinf.result.avg_annual": "Avg. Annual Rate",
    "cinf.result.years": "Period",
    "cinf.result.cpi_from": "CPI (From)",
    "cinf.result.cpi_to": "CPI (To)",
    "cinf.result.interp_label": "Interpretation:",
    "cinf.chart.power_title": "Purchasing Power Over Time",
    "cinf.chart.yoy_title": "Annual Inflation (Dec YoY %)",
    "cinf.table.title": "Annual CPI Data (December)",
    "cinf.table.year": "Year",
    "cinf.table.cpi_index": "CPI Index (Dec)",
    "cinf.table.yoy": "Dec YoY %",
    "cinf.table.cum": "Cumulative from 2004",
    "cinf.table.source_note": "Source: NIS Cambodia. CPI base Oct–Dec 2006 = 100. YoY = December vs. previous December.",
    "cinf.print.note": "All calculations use official NIS Cambodia CPI data. For educational purposes only.",
    "cinf.print.btn": "Print / Save PDF",
    "nssf.page_title": "NSSF Pension Calculator",
    "nssf.page_desc": "Estimate your monthly pension from Cambodia's National Social Security Fund based on your salary and years of contribution.",
    "nssf.bread": "NSSF Pension",
    "nssf.print_title": "NSSF Pension Calculator",
    "nssf.section.personal": "Personal Details",
    "nssf.section.contribution": "NSSF Contribution",
    "nssf.input.current_age": "Current Age",
    "nssf.input.retirement_age": "Retirement Age",
    "nssf.hint.retirement_age": "Cambodia NSSF retirement age: 60",
    "nssf.input.salary": "Average Monthly Salary",
    "nssf.input.start_date": "Contribution Start Date",
    "nssf.hint.start_date": "Date you first enrolled in NSSF",
    "nssf.result.monthly_pension": "Monthly Pension",
    "nssf.result.annual_pension": "Annual Pension",
    "nssf.result.total_years": "Total Contribution Years",
    "nssf.result.retirement_year": "Retirement Year",
    "nssf.result.pension_rate": "Pension Rate",
    "nssf.result.as_pct_salary": "Pension as % of Salary",
    "nssf.result.formula": "Rate Formula:",
    "nssf.warn.under20": "Less than 20 years of contribution — you will receive a lump sum instead of a monthly pension.",
    "nssf.warn.zero_years": "Contribution start date is at or after retirement — no pension accrued.",
    "nssf.chart.title": "Monthly Pension by Years of Contribution",
    "nssf.chart.pension": "Monthly Pension",
    "nssf.chart.you": "Your scenario",
    "nssf.table.title": "Full Calculation Table (Years 1–50)",
    "nssf.table.year": "Year",
    "nssf.table.formula": "Formula",
    "nssf.table.rate": "Rate",
    "nssf.table.monthly": "Monthly Pension",
    "nssf.table.annual": "Annual Pension",
    "nssf.table.age": "Age at Retirement",
    "nssf.source": "Source: Cambodia NSSF. Rate: 1.75%/yr (years 1–15); 1.25%/yr (year 16+); max 70% at 50 years. Minimum 20 years required for monthly pension.",
    "dp.page_title": "Debt Pay-Off Strategies",
    "dti.page_title": "DTI – Debt to Income Ratio",
    "rvb.page_title": "Renting vs. Financing",
    "hvb.page_title": "Savings: Home vs. Bank",
    "calc.animal_budget.name": "Animal Raising Budget",
    "calc.animal_budget.desc": "Calculate whether raising livestock is profitable",
    "budget.section.cycle": "Cycle Details",
    "budget.input.cycle_length": "Months per Cycle",
    "budget.months_suffix": "months",
    "budget.section.income": "Cycle Income",
    "budget.total_income": "Total Cycle Income",
    "budget.section.expense": "Cycle Expenses",
    "budget.total_expense": "Total Cycle Expense",
    "budget.col.amount": "Amount",
    "budget.input.revenue": "Revenue",
    "budget.input.additional_revenue": "Additional Revenue",
    "budget.input.land_rental": "Land Rental Fee",
    "budget.input.transport": "Transportation",
    "budget.input.fuel": "Fuel Expense",
    "budget.input.repair": "Repair & Maintenance",
    "budget.input.other": "Other Expenses",
    "budget.rating.label": "Business Status",
    "budget.stat.net_income": "Net Income",
    "budget.stat.profit_margin": "Profit Margin",
    "budget.monthly.title": "Monthly Summary",
    "budget.stat.monthly_income": "Monthly Income",
    "budget.stat.monthly_expense": "Monthly Expense",
    "budget.stat.monthly_net": "Monthly Net Income",
    "budget.chart.title": "Monthly Income vs Expense",
    "budget.status.high": "High Profit",
    "budget.status.moderate": "Moderate Profit",
    "budget.status.low": "Low Profit",
    "budget.status.loss": "Loss",
    "budget.advice.high": "Excellent earnings! Ready to grow?",
    "budget.advice.moderate": "Good balance! Room to improve.",
    "budget.advice.low": "Thin margin! Let's cut costs.",
    "budget.advice.loss": "In the red! Let's review your costs and pricing.",
    "fb.page_title": "Farming Budget Calculator",
    "fb.page_desc": "Enter your crop's income and expenses for one growing cycle to see if it's profitable — and how it breaks down per month.",
    "fb.bread": "Farming Budget",
    "fb.input.crop": "Crop",
    "fb.crop.rice": "Rice",
    "fb.crop.cassava": "Cassava",
    "fb.crop.cashew": "Cashew",
    "fb.crop.rubber": "Rubber",
    "fb.crop.other": "Other",
    "fb.input.seeds": "Seeds",
    "fb.input.cultivation": "Cultivation",
    "fb.input.hired_help": "Hired Help",
    "fb.input.fertilizer": "Fertilizer / Pesticide / Herbicide",
    "fb.input.equipment": "Equipment",
    "fb.input.tax": "Tax",
    "fb.input.loan_principal": "Loan Principal",
    "fb.input.interest": "Interest",
    "ab.page_title": "Animal Raising Budget Calculator",
    "ab.page_desc": "Enter your livestock income and expenses for one raising cycle to see if it's profitable — and how it breaks down per month.",
    "ab.bread": "Animal Raising Budget",
    "ab.input.animal": "Animal",
    "ab.animal.fish": "Fish",
    "ab.animal.cow": "Cow",
    "ab.animal.pig": "Pig",
    "ab.animal.duck": "Duck",
    "ab.animal.chicken": "Chicken",
    "ab.animal.other": "Other",
    "ab.input.breed": "Animal / Breed Purchase",
    "ab.input.barn": "Barn",
    "ab.input.feed": "Feed",
    "ab.input.supplement": "Supplement Feed",
    "ab.input.water": "Water",
    "ab.input.vaccination": "Vaccination",
    "ab.input.parasite": "Parasite Control",
    "ab.input.labour": "Labour / Salary Expense",
    "ab.input.equipment": "Equipment / Office Materials",
    "invest.bread": "Investment Evaluation",
    "invest.page_desc": "Did your land or property investment beat inflation? Enter the purchase price, year bought, and current value to find out.",
    "invest.note": "<strong>Approximate tool:</strong> Years are calculated by subtracting the purchase year from the current year — no exact dates. Results are a useful guide but should be treated as rough estimates, especially for short holding periods.",
    "invest.card.details": "Investment Details",
    "invest.input.purchase": "Purchase Price",
    "invest.input.year": "Year Bought",
    "invest.input.current": "Current Value",
    "invest.input.inflation": "Average Yearly Inflation",
    "invest.years_from_now": "Years from now =",
    "invest.rounded_note": " ≈ rounded to whole years",
    "invest.inflation_hint": "Cambodia avg. ≈ 2–5%/yr",
    "invest.rating.label": "Investment Rating",
    "invest.rating.good": "Good Investment",
    "invest.rating.good_sub": "Your asset is growing faster than inflation — you are building real purchasing power.",
    "invest.rating.average": "Average Investment",
    "invest.rating.average_sub": "Your asset is roughly keeping pace with inflation — not losing but not gaining real value.",
    "invest.rating.bad": "Bad Investment",
    "invest.rating.bad_sub": "Your asset is losing purchasing power — inflation is eating into its real value.",
    "invest.stat.gain": "Gain / Loss",
    "invest.stat.years": "Years Held",
    "invest.stat.years_sub": "rounded to whole years",
    "invest.stat.cagr": "CAGR (per year)",
    "invest.stat.cagr_sub": "Compound annual growth rate",
    "invest.stat.inflation": "Inflation Rate",
    "invest.stat.inflation_sub": "Average per year",
    "invest.stat.spread": "CAGR vs Inflation",
    "invest.stat.spread_sub": "Positive = beating inflation",
    "invest.stat.simple": "Simple Avg (per year)",
    "invest.stat.simple_sub": "Overstates growth (no compounding)",
    "invest.formula.title": "Why We Use CAGR, Not Simple Average",
    "invest.formula.method": "Method",
    "invest.formula.formula": "Formula",
    "invest.formula.compounding": "Accounts for<br>Compounding?",
    "invest.formula.overstates": "Overstates<br>Growth?",
    "invest.formula.simple_name": "Simple Average",
    "invest.formula.simple_expr": "(Gain ÷ Years) ÷ Cost",
    "invest.formula.cagr_name": "CAGR",
    "invest.formula.cagr_expr": "(End ÷ Start)^(1/n) − 1",
    "invest.formula.simple_compounding": "✗ No",
    "invest.formula.simple_overstates": "✗ Yes",
    "invest.formula.cagr_compounding": "✓ Yes",
    "invest.formula.cagr_overstates": "✓ No",
    "invest.formula.note": "<strong>CAGR</strong> is the preferred measure because it reflects the true compounding effect of holding an asset over time. Simple average inflates the apparent annual return, especially over longer periods.",
    "invest.scale.title": "Rating Scale",
    "invest.scale.good": "✅ Good Investment",
    "invest.scale.good_desc": "CAGR is more than <strong>1% above inflation</strong> — you are meaningfully growing purchasing power.",
    "invest.scale.average": "⚠️ Average Investment",
    "invest.scale.average_desc": "CAGR is within <strong>±1% of inflation</strong> — roughly keeping pace with rising prices, but not growing real value.",
    "invest.scale.bad": "❌ Bad Investment",
    "invest.scale.bad_desc": "CAGR is more than <strong>1% below inflation</strong> — your purchasing power is shrinking.",
    "invest.js.yr_one": "yr",
    "invest.js.yr_many": "yrs",
    "invest.js.same_year": "0 (same year)",
    "invest.js.year_one": "year",
    "invest.js.year_many": "years",
    "invest.js.total": "total",
    "invest.js.pp": "pp",
    "lrs.page_title": "Loan Restructure Comparison",
    "lrs.bread": "Loan Restructure",
    "lrs.print_title": "Loan Restructure Comparison",
    "lrs.page_desc": "Your lender has offered to change your loan. Compare the options side by side — a lower monthly payment usually means paying more interest overall.",
    "lrs.card.inputs": "Your Loan Today",
    "lrs.card.compare": "All Options Compared",
    "lrs.section.options": "What the lender is offering",
    "lrs.input.principal": "Remaining Principal",
    "lrs.input.months": "Remaining Months",
    "lrs.input.rate": "Current Interest Rate",
    "lrs.input.io_months": "Interest-Only Months",
    "lrs.input.ext_months": "Extra Months Added to the Term",
    "lrs.input.new_rate": "Reduced Interest Rate",
    "lrs.input.extra": "Extra Payment You Could Add",
    "lrs.hint.io_months": "Pay only interest for this many months, then go back to the normal payment.",
    "lrs.hint.ext_months": "Stretching the loan lowers each payment but adds interest.",
    "lrs.hint.new_rate": "Applied together with the extra months above.",
    "lrs.hint.extra": "Paying more each month is the only option here that saves you money.",
    "lrs.derived.payment": "Your monthly payment now",
    "lrs.unit.months": "months",
    "lrs.unit.per_year": "% / yr",
    "lrs.th.scenario": "Option",
    "lrs.th.term": "Term",
    "lrs.th.payment": "Monthly Payment",
    "lrs.th.total_interest": "Total Interest",
    "lrs.th.total_paid": "Total Paid",
    "lrs.th.impact": "Impact on Interest",
    "lrs.scenario.current": "Keep current terms",
    "lrs.scenario.io": "Interest-only period",
    "lrs.scenario.extended": "Longer term",
    "lrs.scenario.reduced": "Lower rate + longer term",
    "lrs.scenario.extra": "Pay extra each month",
    "lrs.impact.baseline": "baseline",
    "lrs.impact.more": "more interest",
    "lrs.impact.less": "less interest",
    "lrs.impact.same": "about the same",
    "lrs.then": "then",
    "lrs.never_paid": "Never fully repaid",
    "lrs.check_inputs": "Check your figures",
    "lrs.chart.title": "What You Still Owe Over Time",
    "lrs.chart.start": "Start",
    "lrs.chart.month": "Month",
    "lrs.chart.balance": "Outstanding Balance",
    "lrs.sched.title": "Month-by-Month Schedule",
    "lrs.sched.no": "No.",
    "lrs.sched.payment": "Total Payment",
    "lrs.sched.principal": "Principal",
    "lrs.sched.interest": "Interest",
    "lrs.sched.balance": "Outstanding Balance",
    "lrs.sched.note": "Rows shown in amber are interest-only months — the balance does not go down.",
    "lrs.guide.title": "How to Read This",
    "lrs.guide.current": "<strong>Keep current terms</strong> — nothing changes. Every other row is measured against this one.",
    "lrs.guide.io": "<strong>Interest-only period</strong> — your payment drops to just the interest for a while. The balance does not fall at all during those months, so the loan takes longer and costs more.",
    "lrs.guide.ext": "<strong>Longer term</strong> — the same debt spread over more months. The monthly payment drops the most here, and the total interest rises the most.",
    "lrs.guide.reduced": "<strong>Lower rate + longer term</strong> — the rate falls but the term also stretches. Usually still costs more overall, because the extra months outweigh the cheaper rate.",
    "lrs.guide.extra": "<strong>Pay extra each month</strong> — the only option here that reduces what you pay. The loan finishes early and interest stops sooner.",
    "lrs.guide.warning": "⚠️ <strong>A smaller monthly payment is not the same as a cheaper loan.</strong> Compare the <em>Total Interest</em> column, not the payment.",
    "cmr.period.1": "Period 1",
    "cmr.period.2": "Period 2",
    "cmr.period.3": "Period 3",
    "cmr.period.4": "Period 4",
    "dp.page_desc": "Compare all five pay-off strategies side by side — enter your debts, set your monthly budget, and instantly see which approach gets you debt-free fastest and cheapest.",
    "dp.card.budget": "Monthly Budget for Debt Payments",
    "dp.budget_note": "per month — total available for <strong>all</strong> debts combined",
    "dp.card.debts": "Your Debts",
    "dp.debts_hint": "☰ drag rows · ▲▼ move · Custom order = 🎯 strategy",
    "dp.th.name": "Debt Name",
    "dp.th.balance": "Balance",
    "dp.th.rate": "Rate/yr",
    "dp.th.int_type": "Int. Type",
    "dp.th.min_payment": "Min. Payment",
    "dp.th.penalty": "Penalty",
    "dp.th.per_mo": "/mo",
    "dp.add_debt": "+ Add Another Debt",
    "dp.legend": "<strong>Simple interest</strong> = fixed charge on original balance each month.&nbsp; <strong>Compound</strong> = interest on current balance (most loans).&nbsp; <strong>Penalty /mo</strong> = monthly % charged on the shortfall if you pay less than the minimum.&nbsp; <strong>Rate/yr</strong> = yearly interest rate (e.g. 18%/yr = 1.5%/month).&nbsp; <strong>Min. Payment /mo</strong> = the required monthly payment amount.",
    "dp.card.compare": "All Strategies Compared",
    "dp.th.strategy": "Strategy",
    "dp.th.payoff_order": "Pay-off Order",
    "dp.th.months": "Months",
    "dp.th.total_interest": "Total Interest",
    "dp.th.total_paid": "Total Paid",
    "dp.chart.title": "Remaining Debt Over Time",
    "dp.card.schedule": "Monthly Payment Schedule",
    "dp.strategy.snowball": "⛄ Snowball",
    "dp.strategy.avalanche": "🏔 Avalanche",
    "dp.strategy.stairstepper": "🪜 Stairstepper",
    "dp.strategy.high_payment": "💰 High Payment",
    "dp.strategy.custom": "🎯 Custom",
    "dp.desc.snowball": "Smallest balance first",
    "dp.desc.avalanche": "Highest rate first",
    "dp.desc.stairstepper": "Quickest payoff first",
    "dp.desc.high_payment": "Highest minimum payment first",
    "dp.desc.custom": "Your order (top → bottom)",
    "dp.sched.highlighted": "highlighted",
    "dp.sched.note": "= focus debt getting the extra payment that month. Each row shows exactly how much to pay each lender.",
    "dp.guide.title": "Strategy Guide",
    "dp.guide.snowball_desc": "Pay off the <strong>smallest balance</strong> first. Builds momentum with quick wins. Best for motivation.",
    "dp.guide.avalanche_desc": "Pay off the <strong>highest interest rate</strong> first. Mathematically minimises total interest. Best if disciplined.",
    "dp.guide.stairstepper_desc": "Pay off whichever debt will be eliminated <strong>soonest</strong> with your available extra budget. Frees up cash flow the fastest — re-evaluated after each payoff. A balance between snowball and avalanche.",
    "dp.guide.high_payment_desc": "Pay off the debt with the <strong>highest minimum payment</strong> first. Frees up the largest monthly cash amount when paid off — good if your goal is maximising future cash flow.",
    "dp.guide.custom_desc": "<strong>Your own order</strong>. Drag the rows or use ▲▼ to arrange debts in the order you want to pay them off. The custom strategy follows the table order from top to bottom.",
    "dp.js.compound": "Compound",
    "dp.js.simple": "Simple",
    "dp.js.debt_n": "Debt",
    "dp.js.warn_budget_low": "⚠️ <strong>Budget is less than total minimum payments</strong> — strategies may stall. Increase your monthly budget or reduce minimum payments.",
    "dp.js.warn_interest_exceeds": "⚠️ <strong>Monthly interest on compound loans ({interest}) exceeds your budget ({budget})</strong> — these debts cannot be paid off. Increase your budget or check that rates are per-month (not per-year).",
    "dp.js.best_badge": "✓ Best",
    "dp.js.best_star": "★ Best",
    "dp.js.cannot_pay": "Cannot pay off",
    "dp.js.mo": "mo",
    "dp.js.mo_unpayable": "mo (unpayable)",
    "dp.js.paid_off": "Paid off:",
    "dp.js.interest": "Interest:",
    "dp.js.total_paid": "Total paid:",
    "dp.js.mo_prefix": "mo.",
    "dp.js.details": "▼ details",
    "dp.js.hide": "▲ hide",
    "dp.js.start": "Start",
    "dp.js.mo_short": "Mo.",
    "dp.js.axis_remaining": "Remaining Debt",
    "dp.js.sched_month": "Month",
    "dp.js.sched_total": "Total",
    "currency.label": "Currency:",
    "currency.usd_alt": "USD $",
    "currency.khr_alt": "KHR ៛",
    "currency.exrate_prefix": "1 USD =",
    "dti.heading": "Debt-to-Income (DTI) Ratio",
    "dti.page_desc": "See what percentage of your monthly income goes toward debt payments — and how much room you have to take on a new loan.",
    "dti.bread": "DTI Ratio",
    "dti.print_title": "Debt-to-Income Ratio Calculator",
    "dti.card.current": "Your Current DTI",
    "dti.card.result": "Your DTI Result",
    "dti.card.capacity": "Loan Capacity Analysis",
    "dti.card.borrow": "How Much Can I Borrow?",
    "dti.section.debts": "Monthly Debt Payments",
    "dti.section.obligations": "Ongoing Monthly Obligations",
    "dti.input.income": "Monthly Income",
    "dti.input.housing": "Housing / Rent",
    "dti.input.utilities": "Utilities",
    "dti.input.loans": "Existing Loan Payments",
    "dti.input.other_loans": "Other Loan Payments",
    "dti.input.dti_max": "DTI Maximum (lender cap)",
    "dti.hint.lender_cap": "Most Cambodian lenders prefer ≤40%. International lenders often use 36–43%.",
    "dti.hint.obligations": "Enter your current commitments that would continue if you took a new loan.",
    "dti.result.ratio": "Debt-to-Income Ratio",
    "dti.result.total_debt": "Total Debt Payments",
    "dti.result.income": "Monthly Income",
    "dti.result.available": "Available for Spending",
    "dti.result.housing_share": "Housing Share of Income",
    "dti.result.max_payment": "Maximum New Monthly Payment",
    "dti.result.dti_max_amt": "DTI Max in $",
    "dti.result.obligations": "Current Obligations",
    "dti.result.cap_used": "DTI Cap Used",
    "dti.chart.income_breakdown": "Income Breakdown",
    "dti.chart.loan_capacity": "How Much Can I Loan?",
    "dti.chart.debt_payments": "Debt Payments",
    "dti.chart.loan_cap_series": "Loan Capacity",
    "dti.table.title": "Understanding Your DTI Ratio",
    "dti.table.intro": "Your DTI ratio shows what percentage of your monthly income goes toward debt payments. Lenders use this to assess your ability to take on new loans.",
    "dti.table.range": "DTI Range",
    "dti.table.status": "Status",
    "dti.table.meaning": "What It Means",
    "dti.band.healthy": "✓ Healthy",
    "dti.band.caution": "⚠ Caution",
    "dti.band.highrisk": "✕ High Risk",
    "dti.band.over43": "Over 43%",
    "dti.band.healthy_desc": "Good position for new loans. Most lenders prefer this range.",
    "dti.band.caution_desc": "Some lenders may still approve, but options are limited.",
    "dti.band.highrisk_desc": "Most lenders will decline. Focus on paying down existing debt.",
    "dti.tip": "💡 <strong>Tip:</strong> Adjust your monthly debt payments or income above to see how your DTI changes in real time.",
    "dti.js.over_capacity": "Over capacity — reduce current obligations",
    "dti.js.additional_capacity": "Additional monthly payment capacity",
    "dti.js.used": "used",
    "currency.khr": "៛ KHR",
    "currency.usd": "$ USD",
    "currency.khr_code": "KHR",
    "currency.opt_usd": "USD ($)",
    "currency.opt_khr": "KHR (៛)",
    "rvb.page_desc": "Compare the true long-term cost of buying a home versus renting — including mortgage, taxes, maintenance, and the opportunity cost of your down payment.",
    "rvb.card.buy": "🏠 Home Purchase",
    "rvb.card.rent": "🏘 Renting",
    "rvb.card.invest": "📈 Your Investment Return",
    "rvb.section.annual": "Annual Costs",
    "rvb.section.sale": "Sale",
    "rvb.input.price": "Home Price",
    "rvb.input.down": "Down Payment",
    "rvb.input.rate": "Interest Rate",
    "rvb.input.term": "Loan Term",
    "rvb.input.buy_closing": "Buying Closing Costs",
    "rvb.input.property_tax": "Property Tax",
    "rvb.input.home_ins": "Home Insurance",
    "rvb.input.hoa": "HOA Fee",
    "rvb.input.maintenance": "Maintenance Cost",
    "rvb.input.appreciation": "Home Value Appreciation",
    "rvb.input.sell_closing": "Selling Closing Costs",
    "rvb.input.rent": "Monthly Rent",
    "rvb.input.rent_increase": "Rent Increase",
    "rvb.input.renter_ins": "Renter's Insurance",
    "rvb.input.deposit": "Security Deposit",
    "rvb.input.upfront": "Other Upfront Costs",
    "rvb.input.return": "Average Investment Return",
    "rvb.unit.pct": "%",
    "rvb.unit.pct_yr": "% / yr",
    "rvb.unit.yrs_max": "yrs (max 30)",
    "rvb.unit.per_yr": "/ yr",
    "rvb.unit.per_mo": "/ mo",
    "rvb.hint.financed": "Financed into the loan",
    "rvb.hint.return": "What the down payment could earn if invested elsewhere (e.g., savings account, bonds).",
    "rvb.winner.label": "Better Option",
    "rvb.cost.buy": "🏠 Net Cost of Buying",
    "rvb.cost.rent": "🏘 Net Cost of Renting",
    "rvb.cost.buy_sub": "after home sale proceeds",
    "rvb.cost.rent_sub": "deposit returned at end",
    "rvb.stat.mortgage": "Monthly Mortgage",
    "rvb.stat.down": "Down Payment",
    "rvb.stat.final_value": "Final Home Value",
    "rvb.stat.opp_cost": "Opp. Cost of Down Pmt",
    "rvb.stat.total_rent": "Total Rent Paid",
    "rvb.stat.crossover": "Crossover Year",
    "rvb.chart.title": "Cumulative Net Cost Over Time",
    "rvb.chart.buy": "🏠 Buying Net Cost",
    "rvb.chart.rent": "🏘 Renting Net Cost",
    "rvb.chart.axis": "Net Cost (lower = better)",
    "rvb.chart.note": "Net cost = total money spent minus home equity (buying) or cumulative rent (renting). Lower is better.",
    "rvb.table.title": "Year-by-Year Summary",
    "rvb.table.show": "▼ Show Table",
    "rvb.table.hide": "▲ Hide Table",
    "rvb.th.year": "Year",
    "rvb.th.buying": "🏠 Buying",
    "rvb.th.renting": "🏘 Renting",
    "rvb.th.annual_cost": "Annual Cost",
    "rvb.th.cumulative": "Cumulative",
    "rvb.th.equity": "Home Equity",
    "rvb.th.net": "Net Position",
    "rvb.guide.title": "How This Calculator Works",
    "rvb.guide.buy": "<strong>Buying costs</strong> include: mortgage payments, property tax (grows with home value), home insurance &amp; maintenance (grow with appreciation), HOA fees, and the <em>opportunity cost</em> of your down payment — what it could have earned if invested at your assumed return rate.",
    "rvb.guide.sell": "<strong>Selling costs</strong> (agent fees, transfer tax, etc.) are deducted from the final home value in the net cost calculation.",
    "rvb.guide.rent": "<strong>Renting costs</strong> include monthly rent (growing at your rent-increase rate), renter's insurance, and upfront costs. The security deposit is returned at the end of the term.",
    "rvb.guide.net": "<strong>Net cost</strong> is the total money you end up spending after accounting for the home you own (buy) or the rent you've paid (rent). A lower number means less money spent overall.",
    "rvb.guide.tip": "💡 <strong>Tip:</strong> The crossover year is when buying becomes cheaper than renting on a cumulative basis. Before this point, renting may be financially advantageous.",
    "rvb.js.buy_wins": "Buying is more economical",
    "rvb.js.rent_wins": "Renting is more economical",
    "rvb.js.buy_saving": "Buying saves approximately {amount} compared to renting over {years} years.",
    "rvb.js.rent_saving": "Renting saves approximately {amount} compared to buying over {years} years.",
    "rvb.js.year": "Year",
    "hvb.heading": "Home vs Bank Savings",
    "hvb.bread": "Home vs Bank Savings",
    "hvb.print_title": "Home vs Bank Savings Calculator",
    "hvb.page_desc": "Does starting early matter more than saving longer? Compare an Early Saver, a Late Saver, and keeping cash at home — see which strategy wins over time.",
    "hvb.input.contribution": "Monthly Contribution",
    "hvb.section.age_range": "Age Range",
    "hvb.input.start_age": "Starting Age",
    "hvb.input.end_age": "Ending Age",
    "hvb.section.early_settings": "Early Saver Settings",
    "hvb.input.active_years": "Years of Active Saving",
    "hvb.hint.active_years": "Early saver saves for this many years, then stops and lets interest grow.",
    "hvb.explain": "<strong>🏦 Early Saver</strong> — contributes monthly for the first X years, then <em>stops</em> and lets compound interest do the rest.<br><strong>⏳ Late Saver</strong> — waits X years (saves nothing), then contributes monthly until retirement.<br><strong>🏠 At Home</strong> — saves the same monthly amount as cash with no interest earned.",
    "hvb.card.results": "Results",
    "hvb.strategy.early": "Early Saver",
    "hvb.strategy.late": "Late Saver",
    "hvb.strategy.home": "At Home",
    "hvb.detail.contributed": "Contributed",
    "hvb.detail.interest": "Interest",
    "hvb.detail.active_months": "Active months",
    "hvb.home.no_interest": "No interest earned",
    "hvb.result.total_years": "Total Years",
    "hvb.result.monthly_rate": "Monthly Rate",
    "hvb.result.early_contributes": "Early: Contributes",
    "hvb.result.late_contributes": "Late: Contributes",
    "hvb.chart.title": "Balance Growth Over Time",
    "hvb.sched.title": "Year-by-Year Breakdown",
    "hvb.sched.yr": "Yr",
    "hvb.sched.age": "Age",
    "hvb.sched.contrib": "Contrib.",
    "hvb.sched.balance": "Balance",
    "hvb.head.early": "🏦 Early Saver",
    "hvb.head.late": "⏳ Late Saver",
    "hvb.head.home": "🏠 At Home",
    "hvb.sens.title": "Scenario Sensitivity",
    "hvb.sens.rate_title": "Interest Rate Sensitivity",
    "hvb.sens.years_title": "Active Years Sensitivity",
    "hvb.sens.ages_prefix": "(ages",
    "hvb.sens.active_yrs_suffix": "active yrs)",
    "hvb.sens.rate_mid": ", rate",
    "hvb.sens.rate": "Rate",
    "hvb.sens.active_yrs": "Active Yrs",
    "hvb.sens.winner": "Winner",
    "hvb.js.winner_badge": "★ Winner",
    "hvb.js.wins": "wins",
    "hvb.js.more_than_home": "more than saving at home",
    "hvb.js.early_short": "🏦 Early",
    "hvb.js.late_short": "⏳ Late",
    "cbl.page_title": "Comparing Cambodian Loans",
    "cbl.page_desc": "See the true annual cost of five common Cambodian loan types side by side — some low \"per-cycle\" rates compound into very high yearly costs once fees are included.",
    "cbl.bread": "Comparing Cambodian Loans",
    "cbl.section.shared": "Loan Amount & Comparison Term",
    "cbl.input.principal": "Loan Principal",
    "cbl.input.term": "Comparison Term",
    "cbl.verdict.cheapest": "Cheapest Option",
    "cbl.verdict.priciest": "Most Expensive Option",
    "cbl.section.table": "Compare 5 Loan Types",
    "cbl.col.metric": "Metric",
    "cbl.type.online.name": "1. Online Loan (App-Based)",
    "cbl.type.loyroub.name": "2. Loy Roub (Cycle Loan)",
    "cbl.type.chongkar.name": "3. Chong Kar (Interest-Only)",
    "cbl.type.flat.name": "4. Flat Rate Loan (MFI)",
    "cbl.type.declining.name": "5. Declining Balance (Bank/MFI)",
    "cbl.row.period": "Period Length",
    "cbl.unit.days_cycle": "days/cycle",
    "cbl.unit.months": "months",
    "cbl.row.rate": "Nominal Interest Rate",
    "cbl.unit.pct_cycle": "%/cycle",
    "cbl.unit.pct_month": "%/month",
    "cbl.unit.pct_month_flat": "%/month (flat)",
    "cbl.unit.pct_year_declining": "%/year (declining)",
    "cbl.row.fee": "Upfront Fee Deducted",
    "cbl.row.cash_received": "Cash Actually Received",
    "cbl.row.periods_per_year": "Periods per Year",
    "cbl.row.first_interest": "Interest, First Period",
    "cbl.row.installment": "Installment per Period",
    "cbl.row.total_interest": "Total Interest (over term)",
    "cbl.row.total_repayment": "Total Repayment",
    "cbl.ck.total_repaid_hint": "Total repaid so far (optional)",
    "cbl.ck.open_label": "Still open — no fixed maturity",
    "cbl.row.true_ear": "True EAR (incl. fees)",
    "cbl.row.ear": "EAR / APR (nominal)",
    "cbl.row.rank": "Cost Rank (1 = most expensive)",
    "cbl.row.outstanding": "Principal Outstanding at Year-End",
    "cbl.row.legal": "Legal / Regulatory Status",
    "cbl.legal.online": "Often unlicensed — many app-based lenders operate without NBC approval, which may be against Cambodian law.",
    "cbl.legal.loyroub": "Unregulated — informal lending, not licensed by the National Bank of Cambodia (NBC).",
    "cbl.legal.chongkar": "Unregulated — informal lending, not licensed by the National Bank of Cambodia (NBC).",
    "cbl.legal.flat": "Regulated & licensed by NBC, if the lender is a properly licensed MFI.",
    "cbl.legal.declining": "Regulated & licensed by NBC, if the lender is a properly licensed bank or MFI.",
    "cbl.legal.disclaimer": "This is general market knowledge, not verified against a live official source. Always verify a specific lender's licensing status directly with the National Bank of Cambodia (NBC) before making a decision.",
    "cbl.chart.title": "Nominal EAR vs. True EAR (incl. Fees) by Loan Type",
    "lp.page_title": "Loan Penalties Calculator",
    "lp.page_desc": "See exactly how a late or partial payment splits between penalty, interest, and principal — and what's still owed.",
    "lp.bread": "Loan Penalties Calculator",
    "lp.section.installment": "Overdue Installment",
    "lp.input.overdue_principal": "Overdue Principal",
    "lp.input.overdue_interest": "Overdue Interest",
    "lp.result.overdue_amount": "Overdue Amount",
    "lp.hint.overdue_amount": "Overdue Principal + Overdue Interest",
    "lp.section.rate_timing": "Penalty Rate & Timing",
    "lp.input.annual_penalty_rate": "Annual Penalty Rate (%)",
    "lp.input.due_date": "Due Date",
    "lp.input.actual_date": "Actual Payment Date",
    "lp.hint.actual_date": "Still unpaid? Leave this as today's date.",
    "lp.input.amount_paid": "Amount Paid Toward This Installment",
    "lp.result.daily_penalty_rate": "Daily Penalty Rate (%)",
    "lp.hint.daily_rate": "Annual Rate ÷ 360",
    "lp.result.days_late": "Days Late",
    "lp.section.breakdown": "Penalty & Payment Breakdown",
    "lp.result.penalty_accrued": "Penalty",
    "lp.hint.penalty_accrued": "Full amount accrued to date",
    "lp.result.penalty_paid": "Penalty Paid",
    "lp.result.interest_paid": "Interest Paid",
    "lp.result.principal_paid": "Principal Paid",
    "lp.result.penalty_due": "Penalty Due",
    "lp.result.interest_due": "Interest Due",
    "lp.result.principal_due": "Principal Due",
    "lp.result.total_due": "Total Due",
    "lp.note.priority": "Payment priority is Penalty → Interest → Principal. Overdue penalty and interest are never added to (capitalized into) the principal — there is no compounding.",
    "lp.chart.title": "Outstanding Amount Due by Category"
  },
  "km": {
    "site.name": "ហិរញ្ញវត្ថុឆ្លាតវៃកម្ពុជា",
    "site.tagline": "ឧបករណ៍អប់រំហិរញ្ញវត្ថុ",
    "site.footer.main": "ហិរញ្ញវត្ថុឆ្លាតវៃកម្ពុជា — ការអប់រំផ្នែកហិរញ្ញវត្ថុសម្រាប់ព្រះរាជាណាចក្រកម្ពុជា។",
    "site.footer.edu": "គ្រប់ម៉ាស៊ីនគណនាទាំងនេះ គឺសម្រាប់គោលបំណងអប់រំតែប៉ុណ្ណោះ។ សូមពិគ្រោះយោបល់ជាមួយអ្នកប្រឹក្សាផ្នែកហិរញ្ញវត្ថុសម្រាប់ដំបូន្មានផ្ទាល់ខ្លួន។",
    "site.footer.edu_short": "គ្រប់ម៉ាស៊ីនគណនាទាំងនេះ គឺសម្រាប់គោលបំណងអប់រំតែប៉ុណ្ណោះ។",
    "nav.all": "ម៉ាស៊ីនគណនាទាំងអស់",
    "nav.savings": "ប្រាក់សន្សំ",
    "nav.loans": "ប្រាក់កម្ចី",
    "nav.budgeting": "ថវិកា",
    "nav.fixed": "ប្រាក់បញ្ញើមានកាលកំណត់",
    "nav.monthly": "ការសន្សំប្រចាំខែ",
    "nav.loan": "ម៉ាស៊ីនគណនាប្រាក់កម្ចី",
    "bread.calculators": "ម៉ាស៊ីនគណនា",
    "bread.savings": "ប្រាក់សន្សំ",
    "bread.loans": "ប្រាក់កម្ចី",
    "index.title": "ម៉ាស៊ីនគណនាហិរញ្ញវត្ថុ",
    "index.desc": "ឧបករណ៍ងាយស្រួលប្រើដោយឥតគិតថ្លៃ ដើម្បីជួយលោកអ្នករៀបចំផែនការសន្សំ ស្វែងយល់ពីប្រាក់កម្ចី និងធ្វើការសម្រេចចិត្តផ្នែកហិរញ្ញវត្ថុដោយឈ្លាសវៃ។ រាល់ការគណនាទាំងអស់ នឹងធ្វើឡើងដោយផ្ទាល់នៅក្នុងកម្មវិធីរុករកអ៊ីនធឺណិត (Browser) របស់លោកអ្នក។",
    "index.savings_col": "💰 ម៉ាស៊ីនគណនាប្រាក់សន្សំ",
    "index.loans_col": "🏦ម៉ាស៊ីនគណនាប្រាក់កម្ចី",
    "index.budget_col": "📊 ម៉ាស៊ីនគណនាថវិកា",
    "badge.live": "កំពុងដំណើរការ",
    "badge.soon": "ក្នុងពេលឆាប់ៗនេះ",
    "calc.fixed.name": "ប្រាក់សន្សំមានកាលកំណត់",
    "calc.fixed.desc": "បង្កើនប្រាក់បញ្ញើសរុបក្នុងអត្រាការប្រាក់សមាសតាមពេលវេលា",
    "calc.monthly.name": "ការសន្សំប្រាក់តាមរយៈការបង់វិភាគទានប្រចាំខែ",
    "calc.monthly.desc": "សូមពិនិត្យមើលពីរបៀបដែលការដាក់ប្រាក់ប្រចាំខែទៀងទាត់ ជួយបង្កើនសមតុល្យទឹកប្រាក់របស់អ្នកឱ្យកាន់តែច្រើនឡើង",
    "calc.emergency.name": "មូលនិធិគ្រាអាសន្ន",
    "calc.emergency.desc": "សូមប៉ាន់ប្រមាណទឹកប្រាក់ដែលត្រូវសន្សំសម្រាប់ទុកប្រើប្រាស់ក្នុងគ្រាអាសន្ន ដោយផ្អែកលើការចំណាយជាក់ស្តែងរបស់អ្នក",
    "calc.nssf.name": "ប្រាក់សោធននិវត្តន៍ ប.ស.ស.",
    "calc.nssf.desc": "សូមប៉ាន់ប្រមាណសមតុល្យទឹកប្រាក់នាពេលអនាគតរបស់អ្នក ជាមួយនឹងកម្មវិធីប្រាក់សោធននិវត្តន៍របស់ ប.ស.ស. កម្ពុជា",
    "calc.retire.name": "សមតុល្យទឹកប្រាក់សម្រាប់ពេលចូលនិវត្តន៍នាពេលអនាគត",
    "calc.retire.desc": "សូមគណនាសមតុល្យទឹកប្រាក់សម្រាប់ពេលចូលនិវត្តន៍នាពេលអនាគត នៃគម្រោងសន្សំផ្ទាល់ខ្លួនរបស់អ្នក",
    "calc.homevsbank.name": "ការសន្សំប្រាក់៖ ការរក្សាទុកនៅផ្ទះធៀបនឹងការដាក់ក្នុងធនាគារ",
    "calc.homevsbank.desc": "សូមធ្វើការប្រៀបធៀបរវាងអ្នកសន្សំប្រាក់ចាប់ផ្តើមពីដើមឆ្នាំ និងចុងឆ្នាំ ដោយរក្សាទុកប្រាក់នៅផ្ទះធៀបនឹងការដាក់ក្នុងធនាគារ",
    "calc.invest.name": "ការវាយតម្លៃលើការវិនិយោគ",
    "calc.invest.desc": "សូមធ្វើការវាយតម្លៃថា តើការវិនិយោគនោះកំពុងផ្តល់នូវផលចំណេញសមស្របឬយ៉ាងណា",
    "invest.page_title": "ការវាយតម្លៃលើការវិនិយោគ",
    "calc.simple_daily.name": "ការប្រាក់សាមញ្ញ - ប្រចាំថ្ងៃ",
    "calc.simple_daily.desc": "សូមគណនាការប្រាក់កម្ចីប្រចាំថ្ងៃ និងស្វែងរកអត្រាការប្រាក់ដែលមិនទាន់ដឹង",
    "calc.simple_monthly.name": "ការប្រាក់សាមញ្ញ - ប្រចាំខែ/ប្រចាំឆ្នាំ",
    "calc.simple_monthly.desc": "ការប្រាក់សាមញ្ញប្រចាំខែ ឬប្រចាំឆ្នាំ និងការស្វែងរកអត្រាការប្រាក់ដែលមិនទាន់ដឹង",
    "calc.loan4.name": "ម៉ាស៊ីនគណនាប្រាក់កម្ចី (៤ ផ្នែក)",
    "calc.loan4.desc": "សូមគណនាស្វែងរកផ្នែកណាមួយនៃប្រាក់កម្ចីដែលនៅខ្វះ (ប្រាក់ដើម អត្រាការប្រាក់ រយៈពេលកម្ចី ឬការបង់ប្រាក់ប្រចាំខែ)",
    "calc.compound_loan.name": "ប្រាក់កម្ចីការប្រាក់សមាស",
    "calc.compound_loan.desc": "តារាងសងប្រាក់កម្ចីពេញលេញ ដោយរាប់បញ្ចូលថ្ងៃឈប់សម្រាក និងការកែសម្រួលថ្ងៃទូទាត់",
    "calc.loan_flexible.name": "ប្រាក់កម្ចីបែបបត់បែន (ដើមតុនជាកម្រើក)",
    "calc.loan_flexible.desc": "ការប្រាក់គិតប្រចាំខែ ដើមតុនសងជាដុំតាមកំណត់",
    "calc.loan_multi_rate.name": "ប្រាក់កម្ចី — អត្រាច្រើន",
    "calc.loan_multi_rate.desc": "ប្រាក់កម្ចីដែលមានការប្រែប្រួលអត្រា មានការគណនាការប្រាក់ពិន័យ",
    "calc.loan_adjusted.name": "ការប្រៀបធៀបការរចំសម្រួលប្រាក់កម្ចី",
    "calc.loan_adjusted.desc": "ប្រៀបធៀបលក្ខខណ្ឌប្រាក់កម្ចីបច្ចុប្បន្ន និងដែលបានស្នើរ — គណនាការបង់តិច និងការប្រែប្រួលអត្រា",
    "calc.loan_comp.name": "ការប្រៀបធៀបកម្ចី",
    "calc.loan_comp.desc": "ការប្រៀបធៀបគ្នារវាង បង់ថេរ និង បង់ថយ",
    "calc.promo.name": "កម្ចីដែលមានការផ្តល់ជូនពិសេស",
    "calc.promo.desc": "កម្ចីដែលមានរយៈពេលអនុវត្តអត្រាការប្រាក់ខុសៗគ្នា",
    "calc.cambodia_loans.name": "ការប្រៀបធៀបកម្ចីនៅកម្ពុជា",
    "calc.cambodia_loans.desc": "ការប្រៀបធៀបប្រភេទកម្ចីទូទៅដែលមាននៅកម្ពុជា",
    "calc.credit_card.name": "បំណុលកាតឥណទាន",
    "calc.credit_card.desc": "ការស្វែងយល់ពីចំណាយពិតប្រាកដនៃសមតុល្យបំណុលកាតឥណទាន",
    "calc.debt_payoff.name": "យុទ្ធសាស្ត្រក្នុងការទូទាត់សងបំណុល",
    "calc.debt_payoff.desc": "វិធីសាស្ត្រល្អបំផុត ដើម្បីសងបំណុលច្រើនក្នុងពេលតែមួយ",
    "calc.dti.name": "អត្រាលទ្ធភាពកម្ចី (DTI)",
    "calc.dti.desc": "គណនាលទ្ធភាពរបស់អ្នកចំពោះកម្ចីទិញផ្ទះ និងបំណុលផ្សេងៗ",
    "calc.rent_vs_buy.name": "ការជួលផ្ទះ ប្រៀបធៀបនឹង ការបង់រំលស់",
    "calc.rent_vs_buy.desc": "តើការជួល ឬការបង់រំលស់ផ្ទះមួយណាដែលមានភាពសន្សំសំចៃជាង?",
    "calc.family_budget.name": "ថវិកាគ្រួសារ",
    "calc.family_budget.desc": "ការរៀបចំផែនការថវិកាគ្រួសារជាមូលដ្ឋាន",
    "calc.church_budget.name": "ថវិកាក្រុមជំនុំ",
    "calc.church_budget.desc": "ឧបករណ៍សាមញ្ញសម្រាប់រៀបចំថវិកាក្រុមជំនុំ",
    "calc.farm_budget.name": "ថវិកាកសិកម្ម",
    "calc.farm_budget.desc": "គណនាដើម្បីដឺងថាតើដំណាំផ្តល់ផលចំណេញដែរឬទេ",
    "calc.insurance.name": "ធានារ៉ាប់រង – បញ្ចប់មុនកំណត់?",
    "calc.insurance.desc": "ការវាយតម្លៃថាតើការលុបចោលកិច្ចសន្យាធានារ៉ាប់រងគឺជាជម្រើសដ៏ល្អឬយ៉ាងណា",
    "calc.inflation.name": "ឧបករណ៍គណនាអតិផរណានៅកម្ពុជា",
    "calc.inflation.desc": "តើប្រាក់ចំនួននេះ មានតម្លៃស្មើនឹងប៉ុន្មាននៅក្នុងពេលបច្ចុប្បន្ន?",
    "input.label": "ការបញ្ចូល",
    "input.main": "ការបញ្ចូលសំខាន់ៗ",
    "input.optional": "ការកំណត់បន្ថែម (ជម្រើស)",
    "input.annual_rate": "អត្រាការប្រាក់ប្រចាំឆ្នាំ",
    "input.time_period": "រយៈពេល",
    "input.unit": "ឯកតា",
    "input.years": "ឆ្នាំ",
    "input.months": "ខែ",
    "input.comp_freq": "ភាពញឹកញាប់នៃការទូទាត់ការប្រាក់សមាស",
    "input.freq.monthly": "ប្រចាំខែ",
    "input.freq.quarterly": "ប្រចាំត្រីមាស",
    "input.freq.semi": "ប្រចាំឆមាស",
    "input.freq.annual": "ប្រចាំឆ្នាំ",
    "input.freq.daily": "ប្រចាំថ្ងៃ",
    "input.nationality": "ប្រភេទអ្នកដាក់ប្រាក់",
    "input.nat.national": "ជនជាតិខ្មែរ (ពន្ធ ៦%)",
    "input.nat.foreigner": "បរទេស (ពន្ធ ១២%)",
    "input.days_unit": "ថ្ងៃ",
    "btn.calculate": "គណនា",
    "result.summary": "លទ្ធផលសង្ខេប",
    "result.effective_rate": "អត្រាផលចំណេញប្រចាំឆ្នាំជាក់ស្តែង",
    "result.rule72": "ឆ្នាំដើម្បីគុណទ្វេដង (ច្បាប់លេខ ៧២)",
    "result.quick_cmp": "ការប្រៀបធៀបដោយសង្ខេប",
    "cmp.scenario": "សេណារីយ៉ូ",
    "cmp.future_value": "តម្លៃអនាគត",
    "cmp.current": "▶ គម្រោងបច្ចុប្បន្ន",
    "cmp.plus1": "ប្រសិនបើអត្រាការប្រាក់កើនឡើង ១%",
    "cmp.minus1": "ប្រសិនបើអត្រាការប្រាក់ថយចុះ ១%",
    "cmp.double_time": "ការបង្កើនពេលវេលាទ្វេដង",
    "fixed.page_title": "ម៉ាស៊ីនគណនាប្រាក់សន្សំមានកាលកំណត់",
    "fixed.page_desc": "ស្វែងយល់ពីរបៀបដែលការដាក់ប្រាក់របស់អ្នកកើនឡើងតាមពេលវេលា ដោយសារការប្រាក់សមាស",
    "fixed.bread": "ម៉ាស៊ីនគណនាប្រាក់សន្សំមានកាលកំណត់",
    "fixed.print_title": "ម៉ាស៊ីនគណនាប្រាក់សន្សំមានកាលកំណត់",
    "fixed.input.principal": "ទឹកប្រាក់ដាក់បញ្ញើដំបូង",
    "fixed.result.future_value_net": "ក្រោយ-តម្លៃអនាគតពន្ធ",
    "fixed.result.principal": "ទឹកប្រាក់ដាក់បញ្ញើដំបូង",
    "fixed.result.gross_interest": "ការប្រាកមុនកាត់ពន្ធ",
    "fixed.result.tax_deducted": "ពន្ធបានកាត់",
    "fixed.result.net_interest": "ការប្រាកក្រោយកាត់ពន្ធ",
    "fixed.chart.title": "តារាងបង្ហាញកំណើនប្រាក់សន្សំ",
    "fixed.chart.net_balance": "ក្រោយ-សមតុល្យពន្ធ",
    "fixed.chart.gross_balance": "សមតុល្យដុល(មុនពេលកាត់ពន្ធ)",
    "fixed.chart.principal": "ប្រាក់ដើម",
    "cmp.fixed.half": "ប្រសិនបើទឹកប្រាក់បញ្ញើកាត់បន្ថយពាក់កណ្តាល",
    "cmp.fixed.double": "ប្រសិនបើទឹកប្រាក់បញ្ញើកើនឡើងទ្វេដង",
    "simple_monthly.page_title": "ម័ស៊ឹនគណនាការសងប្រចាំខែ/ឆ្នាំ",
    "simple_monthly.page_desc": "គណនាការប្រាក់ និងកាលវិភាគសង សម្រាប់ប្រាក់កម្ចីការប្រាក់សាមញ្ញ។ ជ្រើសរើសថាតើការប្រាក់គិតប្រចាំខែ ឬប្រចាំឆ្នាំ ហើយថាតើគិតលើប្រាក់ដើមដំបូង ឬប្រាក់ដើមនៅសល់។",
    "simple_monthly.bread": "ការប្រាក់សាមញ្ញ – ប្រចាំខែ/ឆ្នាំ",
    "simple_monthly.print_title": "ម័ស៊ឹនគណនាការសងប្រចាំខែ/ឆ្នាំ",
    "simple_monthly.card.payment": "ការកំណត់ការទូទាត់",
    "simple_monthly.input.rate": "អត្រាការប្រាក់",
    "simple_monthly.input.rate_period": "រយៈពេលអត្រា",
    "simple_monthly.input.period.monthly": "ក្នុងមួយខែ",
    "simple_monthly.input.period.yearly": "ក្នុងមួយឆ្នាំ",
    "simple_monthly.input.interest_base": "គណនាការប្រាក់លើ",
    "simple_monthly.input.base.original": "ប្រាក់ដើមដំបូង",
    "simple_monthly.input.base.remaining": "ប្រាក់ដើមនៅសល់",
    "simple_monthly.input.principal_label": "ការកាត់បន្ថយប្រាក់ដើម (ជម្រើស)",
    "simple_monthly.input.principal_hint": "កំណត់ការទូទាត់ប្រចាំខែដែលច្រើនជាងការប្រាក់ ដើម្បីចាប់ផ្ដើមសងដើមតុន។",
    "simple_monthly.input.new_payment": "ការទូទាត់ប្រចាំខែ",
    "simple_monthly.input.new_payment_date": "ថ្ងៃចាប់ផ្ដើមបង់សង (ជម្រើស)",
    "simple_monthly.result.total_repaid": "ចំនួនទឹកប្រាក់សរុបបានសង",
    "simple_monthly.result.interest_only": "ការប្រាក់ប្រចាំខែ",
    "simple_monthly.result.never_paid": "គ្មានថ្ងៃបញ្ចប់",
    "simple_monthly.result.never_paid_hint": "ប្រាក់កម្ចីមិនត្រូវបានសង — កំណត់ការទូទាត់ច្រើនជាងការប្រាក់ ដើម្បីសងប្រាក់ដើម",
    "simple_monthly.result.total_interest": "ការប្រាក់សរុបបានបង់",
    "simple_monthly.result.monthly_interest": "ការប្រាក់ប្រចាំខែ",
    "simple_monthly.result.yearly_interest": "ការប្រាក់ប្រចាំឆ្នាំ",
    "simple_monthly.result.term": "រយៈពេលកម្ចី",
    "simple_monthly.result.months": "ខែ",
    "simple_monthly.result.partial": "សង់ប្រាក់ដើមខ្លះ",
    "simple_monthly.per_month": "/ខែ",
    "simple_monthly.per_year": "/ឆ្នាំ",
    "simple_monthly.chart.title": "ប្រាក់ដើមនៅសល់តាមពេលវេលា",
    "simple_monthly.chart.balance": "ប្រាក់ដើមនៅសល់",
    "simple_monthly.sched.month": "ខែ",
    "simple_monthly.sched.interest": "ការប្រាក់",
    "simple_monthly.sched.payment": "ការទូទាត់",
    "simple_monthly.sched.principal_paid": "ប្រាក់ដើមបានបង់",
    "simple_monthly.sched.never_paid_note": "លំនាំនេះបន្តគ្មានទីបញ្ចប់។ កំណត់ការទូទាត់ប្រចាំខែច្រើនជាងការប្រាក់ ដើម្បីសងប្រាក់កម្ចី។",
    "simple_daily.page_title": "ម៉ាស៊ឹនគណនាការប្រាក់សាមញ្ញសងការប្រាក់ប្រចាំថ្ងៃ",
    "simple_daily.page_desc": "បញ្ចូលចំនួនប្រាក់កម្ចឹ និងចំនួនប្រាក់សរុបដែលត្រូវសង ដើម្បីមើលការទូទាត់ប្រចាំថ្ងៃ និងអត្រាការប្រាក់ប្រចាំឆ្នាំពិតប្រាកដ មានរហូតដល់៣ជម្រើសនៃរយៈពេលសង",
    "simple_daily.bread": "ការប្រាក់សាមញ្ញ – ប្រចាំថ្ងៃ",
    "simple_daily.print_title": "ម៉ាស៊ឹនគណនាការប្រាក់សាមញ្ញសងការប្រាក់ប្រចាំថ្ងៃ",
    "simple_daily.input.currency": "រូបិយបណ្ណ",
    "simple_daily.input.loan": "ចំនួនប្រាក់កម្ចឹ (ប្រាក់ដើម)",
    "simple_daily.input.payback": "ចំនួនប្រាក់ត្រូវសង​ (ចំនួនប្រាក់សរុបត្រូវបង់សងមកវិញ)",
    "simple_daily.input.start_date": "កាលបរិច្ឆេតផ្ដើមប្រាក់កម្ចឹ (ជម្រើស)",
    "simple_daily.input.options_label": "ជម្រើសរយៈពេលបង់សង",
    "simple_daily.input.opt1": "ជម្រើស ១",
    "simple_daily.input.opt2": "ជម្រើស ២",
    "simple_daily.input.opt3": "ជម្រើស ៣",
    "simple_daily.result.total_interest": "ការប្រាក់សរុប (ប្រាក់ចំណេញរបស់ម្ចាស់កម្ចី)",
    "simple_daily.result.loan_amount": "ចានប្រាកកម្ចឹ",
    "simple_daily.result.payback_amount": "ប្រាក់សងសរុប",
    "simple_daily.result.comparison": "ការប្រើបធ្រឹជម្រើស",
    "simple_daily.result.option_col": "ជម្រើស",
    "simple_daily.result.days_col": "ថ្ងៃ",
    "simple_daily.result.daily_pmt_col": "ការតូតកាត់ប្រចាំថ្ងៃ",
    "simple_daily.result.annual_rate_col": "អត្រាប្រចាំឆ្នាំ",
    "simple_daily.chart.title": "សមតុល្យប្រចាំថ្ងៃដែលនៅសល់",
    "simple_daily.chart.opt1": "ជម្រើស ១",
    "simple_daily.chart.opt2": "ជម្រើស ២",
    "simple_daily.chart.opt3": "ជម្រើស ៣",
    "simple_daily.sched.day": "ថ្ងៃ",
    "simple_daily.sched.date": "កាលបរិច្ឆេត",
    "monthly.page_title": "ម៉ាស៊ីនគណនាប្រាក់សន្សំតាមការបង់ប្រាក់ប្រចាំខែ",
    "monthly.page_desc": "ស្វែងយល់ពីរបៀបដែលការដាក់ប្រាក់ប្រចាំខែទៀងទាត់ (ដោយមាន ឬគ្មានទឹកប្រាក់ដំបូង) កើនឡើងតាមពេលវេលា",
    "monthly.bread": "ម៉ាស៊ីនគណនាប្រាក់សន្សំតាមការបង់ប្រាក់ប្រចាំខែ",
    "monthly.print_title": "ម៉ាស៊ីនគណនាប្រាក់សន្សំតាមការបង់ប្រាក់ប្រចាំខែ",
    "monthly.input.contrib": "ការបង់ប្រាក់ប្រចាំខែ",
    "monthly.input.principal": "ទឹកប្រាក់ដាក់បញ្ញើដំបូង (ជាជម្រើស)",
    "monthly.input.timing": "ពេលវេលានៃការបង់ប្រាក់សន្សំ",
    "monthly.timing.end": "ចុងគ្រា",
    "monthly.timing.begin": "ដើមគ្រា",
    "monthly.result.future_value": "តម្លៃអនាគត",
    "monthly.result.future_value_net": "ក្រោយ-តម្លៃអនាគតពន្ធ",
    "monthly.result.principal": "ទឹកប្រាក់ដាក់បញ្ញើដំបូង",
    "monthly.result.total_contribs": "ទឹកប្រាក់សន្សំសរុប",
    "monthly.result.total_principal": "សរុបប្រាក់ដើមវិនិយោគ",
    "monthly.result.total_interest": "សរុបការប្រាក់ទទួលបាន",
    "monthly.result.gross_interest": "ការប្រាកមុនកាត់ពន្ធ",
    "monthly.result.tax_deducted": "ពន្ធបានកាត់",
    "monthly.result.net_interest": "ការប្រាកក្រោយកាត់ពន្ធ",
    "monthly.chart.title": "តារាងកំណើនប្រាក់សន្សំ",
    "monthly.chart.balance": "សមតុល្យបន្ទាប់ពីបង់ពន្ធ",
    "monthly.chart.gross_balance": "សមតុល្យដុល(មុនពន្ធ)",
    "monthly.chart.invested": "ទឹកប្រាក់វិនិយោគសរុប",
    "cmp.monthly.lump_only": "ចំនួនប្រាក់សរុបប៉ុណ្ណោះ (គ្មានប្រចាំខែ)",
    "cmp.monthly.month_only": "ប្រចាំខែប៉ុណ្ណោះ (គ្មានចំនួនប្រាក់សរុប)",
    "loan.page_title": "ម៉ាស៊ីនគណនាប្រាក់កម្ចី (៤ ផ្នែក)",
    "loan.page_desc": "ប្រសិនបើអ្នកមានទិន្នន័យ ៣ ក្នុងចំណោម ៤ នៃកត្តាកម្ចី (ទឹកប្រាក់ដើម, អត្រាការប្រាក់, ចំនួនត្រូវបង់, ឬរយៈពេលកម្ចី) អ្នកអាចគណនាដើម្បីរកកត្តាដែលនៅសល់មួយទៀតបាន",
    "loan.bread": "ម៉ាស៊ីនគណនាប្រាក់កម្ចី (៤ ផ្នែក)",
    "loan.print_title": "ម៉ាស៊ីនគណនាប្រាក់កម្ចី (៤ ផ្នែក)",
    "loan.section.currency": "រូបិយប័ណ្ណ",
    "loan.exrate": "អត្រាប្តូរូបិយប័ណ្ណ (1 ដុល្លារ =)",
    "loan.section.solve": "ស្វែងរក",
    "loan.solve.payment": "ការទូទាត់\nប្រចាំខែ",
    "loan.solve.principal": "ទឹកប្រាក់\nកម្ចី\n",
    "loan.solve.rate": "អត្រា\nការប្រាក់",
    "loan.solve.nper": "រយៈពេល\nកម្ចី",
    "loan.section.details": "ព័ត៌មានលម្អិតនៃប្រាក់កម្ចី",
    "loan.input.principal": "ទឹកប្រាក់កម្ចី",
    "loan.input.rate": "អត្រាការប្រាក់ប្រចាំឆ្នាំ",
    "loan.input.term": "រយៈពេលកម្ចី",
    "loan.input.payment": "ការទូរទាត់ប្រចាំខែ",
    "loan.result.principal": "ទឹកប្រាក់កម្ចី",
    "loan.result.payment": "ការទូរទាត់ប្រចាំខែ",
    "loan.result.total_paid": "ទឹកប្រាក់សរុបបានបង់",
    "loan.result.total_interest": "ការប្រាក់សរុបបានបង់",
    "loan.result.interest_pct": "ការប្រាក់គិតជាភាគរយ (%) នៃទឹកប្រាក់ដើម",
    "loan.result.term": "រយៈពេលកម្ចី",
    "loan.hero.payment": "ការទូរទាត់ប្រចាំខែ",
    "loan.hero.principal": "ទឹកប្រាក់កម្ចី",
    "loan.hero.rate": "អត្រាការប្រាក់ប្រចាំឆ្នាំ",
    "loan.hero.nper": "ទឹកប្រាក់កម្ចី",
    "loan.chart.title": "សមតុល្យប្រាក់កម្ចីតាមពេលវេលា",
    "loan.chart.balance": "សមតុល្យដែលនៅសល់",
    "loan.chart.cum_interest": "ចំនួនការប្រាក់សរុបបានបង់",
    "loan.schedule.title": "តារាងកាលវិភាគនៃការសងប្រាក់កម្ចី",
    "loan.sched.payment_num": "ការទូទាត់ #",
    "loan.sched.payment": "ការទូទាត់",
    "loan.sched.principal": "ប្រាក់ដើម",
    "loan.sched.remaining": "សមតុល្យដែលនៅសល់",
    "cmp.loan.header.pmt": "ការទូទាត់ប្រចាំខែ",
    "cmp.loan.header.int": "ការប្រាក់សរុប",
    "cmp.loan.plus1": "ការកើនឡើងអត្រាការប្រាក់ ១%",
    "cmp.loan.minus1": "ការកាត់បន្ថយអត្រាការប្រាក់ ១%",
    "cmp.loan.1yr": "រយៈពេលកម្ចី ១ ឆ្នាំ",
    "cmp.loan.3yr": "រយៈពេលកម្ចី ៣ ឆ្នាំ",
    "schedule.title": "កាលវិភាគនៃការសងប្រាក់កម្ចីតាមដំណាក់កាលនីមួយៗ",
    "schedule.show": "បង្ហាញកាលវិភាគ",
    "schedule.hide": "លាក់កាលវិភាគ",
    "sched.period": "គ្រា",
    "sched.date": "កាលបរិច្ឆេទ",
    "sched.beg_balance": "សមតុល្យដើមគ្រា",
    "sched.interest": "ការប្រាក់ដែលទទួលបាន",
    "sched.gross_interest": "ការប្រាក់ដុល",
    "sched.tax": "ពន្ធ",
    "sched.net_interest": "ការប្រាក់សុទ្ធ",
    "sched.end_balance": "សមតុល្យចុងគ្រា",
    "sched.cum_interest": "ការប្រាក់សរុប",
    "sched.cum_net_interest": "ការប្រាក់សរុប",
    "sched.cum_contribs": "ការដាក់ប្រាក់សរុប",
    "fl.page_title": "ប្រាក់កម្ចីបែបបត់បែន — ប្រាក់ដើមប្រចាំកាល",
    "fl.page_desc": "ការប្រាក់ត្រូវបានគណនាប្រចាំខែតាមសមត្យលប្រាក់ដើមនៅសល់។ ប្រាក់ដើមត្រូវបានសងជាដុំតាមអំឡុងពេលកំណត់ ។ បង្កើតកាលវិភាគពេញលេញ ជាមួយការគេចថ្ងៃបុណ្យ។",
    "fl.bread": "ប្រាក់កម្ចីបែបបត់បែន",
    "fl.print_title": "ម៉ាស៊ីនគណនាកម្ចីបត់បែន",
    "fl.section.loan": "ព័ត៌មានប្រាក់កម្ចី",
    "fl.section.dates": "កាលបរិច្ឆេត",
    "fl.section.settings": "ការកំណត់",
    "fl.section.structure": "រចនាសម្ព័ន្ធការទូទាត់",
    "fl.input.loan_amount": "ចំនួនប្រាក់កម្ចី",
    "fl.input.rate": "អត្រាការប្រាក់ប្រចាំឆ្នាំ",
    "fl.input.term": "រយៈពេលកម្ចី",
    "fl.input.start_date": "ថ្ងៃចាប់ផ្ដើមប្រាក់កម្ចី",
    "fl.input.override_date": "ថ្ងៃចាប់ផ្ដើមជំនួស",
    "fl.input.override_hint": "ជម្រើស – ជំនួសកាលបរិច្ឆេតយោងសម្រាប់ការគណនាថ្ងៃដំបូង",
    "fl.input.first_payment": "ថ្ងៃទូទាត់ដំបូង",
    "fl.input.day_count": "វិធីគណនាថ្ងៃ",
    "fl.day_count.standard": "ស្ដង់ដារ – ថ្ងៃពិតប្រាកដ / 360",
    "fl.day_count.actual": "ពិតប្រាកដ – ថ្ងៃពិតប្រាកដ / 365",
    "fl.input.delay_rule": "ច្បាប់ថ្ងៃទូទាត់",
    "fl.delay.none": "គ្មានការកែតម្រូវ",
    "fl.delay.skip_sun": "គេចថ្ងៃអាទិត្យ",
    "fl.delay.skip_sat_sun": "គេចថ្ងៃសៅរ៍ និងអាទិត្យ",
    "fl.delay.skip_sun_hol": "គេចថ្ងៃអាទិត្យ និងបុណ្យជាតិ",
    "fl.delay.skip_all": "គេចថ្ងៃសៅរ៍ អាទិត្យ និងបុណ្យជាតិ",
    "fl.input.frequency": "ចំនួនខែរវាងការសងដើមតុន",
    "fl.input.frequency_unit": "ខែ",
    "fl.input.freq_start": "ថ្ងៃចាប់ផ្ដើមវដ្ត",
    "fl.input.fixed_principal": "ដើមតុនថែរ / ការទូទាត់",
    "fl.principal.auto": "ស្វ័យប្រវត្តិ",
    "fl.principal.reset": "កំណត់ស្វ័យប្រវត្តិ",
    "fl.input.defer": "ពន្យារការប្រាក់ទៅថ្ងៃទូទាត់",
    "fl.defer.no": "ទេ – បង់ការប្រាក់ប្រចាំខែ",
    "fl.defer.yes": "បាទ/ចាស – ប្រមូល ហើយបង់ជាមួយដើមតុន",
    "fl.result.monthly_interest": "ការប្រាក់ប្រចាំខែ (ធម្មតា)",
    "fl.result.lump_sum": "ប្រាក់ដើមសរុប",
    "fl.result.total_paid": "ចំនួនទឹកប្រាក់សរុបបានបង់",
    "fl.result.total_principal": "ប្រាក់ដើមសរុប",
    "fl.result.total_interest": "ការប្រាក់សរុប",
    "fl.result.maturity": "ថ្ងៃផុតកំណត់",
    "fl.chart.title": "សមតុល្យប្រាក់កម្ចីតាមពេលវេលា",
    "fl.chart.balance": "សមតុល្យដែលនៅសល់",
    "fl.chart.cum_interest": "ការប្រាក់សរុបបំរើ",
    "fl.sched.title": "កាលវិភាគសងប្រាក់",
    "fl.sched.num": "ល.រ",
    "fl.sched.date": "ថ្ងៃទូទាត់",
    "fl.sched.days": "ថ្ងៃ",
    "fl.sched.principal": "ប្រាក់ដើម",
    "fl.sched.interest": "ការប្រាក់",
    "fl.sched.total": "សរុប",
    "fl.sched.balance": "សមតុល្យ",
    "fl.sched.totals": "សរុបទាំងអស់",
    "ef.page_title": "ម៉ាស៊ឹនគណនាមូលនិធិគ្រាអាសន្ន",
    "ef.page_desc": "បញ្ចូលការចំណាយប្រចាំខែ ដើម្បីដឹងថាតើអ្នកត្រូវការប្រាក់ប៉ុន្មានសម្រាប់មូលនិធិគ្រាអាសន្ន។ អ្នកជំនាញណែនាំឱ្យសន្សំ ៣-៦ ខែ នៃការចំណាយ។",
    "ef.bread": "មូលនិធិគ្រាអាសន្ន",
    "ef.print_title": "ម៉ាស៊ឹនគណនាមូលនិធិគ្រាអាសន្ន",
    "ef.section.expenses": "ការចំណាយប្រចាំខែ",
    "ef.col.amount": "ចំនួន",
    "ef.input.housing": "លំនៅដ្ឋាន (ថ្លៃជួល, ភ្លើង, ទឹក)",
    "ef.input.food": "អាហារ",
    "ef.input.transport": "មធ្យោបាយធ្វើដំណើរ",
    "ef.input.debt": "ការសងបំណុល",
    "ef.input.education": "ការអប់រំកូន",
    "ef.input.phone": "ទូរស័ព្ទ",
    "ef.input.insurance": "ធានារ៉ាប់រង",
    "ef.input.property_tax": "ពន្ធដីធ្លី",
    "ef.input.other": "ផ្សេងៗ",
    "ef.total": "ការចំណាយប្រចាំខែសរុប",
    "ef.goals.title": "គោលដៅមូលនិធិគ្រាអាសន្ន",
    "ef.level.basic_dot": "មូលដ្ឋាន",
    "ef.level.good_dot": "ល្អ",
    "ef.level.better_dot": "ល្អជាង",
    "ef.level.basic_desc": "ការចំណាយ ១ ខែ",
    "ef.level.good_desc": "ការចំណាយ ៣ ខែ",
    "ef.level.better_desc": "ការចំណាយ ៦ ខែ",
    "ef.goal.basic": "១ ខែ - មូលដ្ឋាន",
    "ef.goal.basic_sub": "អប្បបរមាដែលណែនាំ",
    "ef.goal.good": "៣ ខែ - ល្អ",
    "ef.goal.good_sub": "ការណែនាំស្ដង់ដារ",
    "ef.goal.better": "៦ ខែ - ល្អជាង",
    "ef.goal.better_sub": "ការអនុវត្តល្អបំផុត",
    "ef.chart.title": "គោលដៅមូលនិធិគ្រាអាសន្ន",
    "cln.page_title": "ប្រាក់កម្ចីការប្រាក់ផ្សំ",
    "cln.page_desc": "បង្កើតកាលវិភាគសងប្រាក់ពេញលេញដោយផ្អែកលើកាលបរិច្ឆេត។ ជ្រើស 30/360 ឬ Actual/360 ហើយដំណើរការដោយស្វ័យប្រវត្តិ ដើម្បីគេចថ្ងៃអាទិត្យ ឬថ្ងៃបុណ្យជាតិ។",
    "cln.bread": "ប្រាក់កម្ចីការប្រាក់ផ្សំ",
    "cln.print_title": "ម័ស៊ឹនគណនាប្រាក់កម្ចីការប្រាក់ផ្សំ",
    "cln.input.loan_amount": "ចំនួនប្រាក់កម្ចី",
    "cln.input.rate": "អត្រាការប្រាក់ប្រចាំឆ្នាំ",
    "cln.input.term": "រយៈពេលកម្ចី",
    "cln.input.start_date": "ថ្ងៃចាប់ផ្ដើមប្រាក់កម្ចី",
    "cln.input.first_payment": "ថ្ងៃទូទាត់ដំបូង",
    "cln.input.day_count": "វិធីគណនាថ្ងៃ",
    "cln.day_count.30_360": "30/360 (អត្រា ÷ 12)",
    "cln.day_count.actual_360": "Actual/360 (អត្រា ÷ 360 × ថ្ងៃ)",
    "cln.input.delay_rule": "ច្បាប់ថ្ងៃទូទាត់",
    "cln.delay.none": "គ្មានការកែតម្រូវ",
    "cln.delay.skip_sun": "គេចថ្ងៃអាទិត្យ → ថ្ងៃច័ន្ទ",
    "cln.delay.skip_sun_hol": "គេចថ្ងៃអាទិត្យ និងបុណ្យជាតិ",
    "cln.delay.skip_sat_sun": "គេចថ្ងៃសៅរ៍ និងអាទិត្យ → ថ្ងៃច័ន្ទ",
    "cln.delay.skip_sat_sun_hol": "គេចថ្ងៃសៅរ៍ អាទិត្យ និងបុណ្យជាតិ",
    "cln.input.payment": "ការទូទាត់ប្រចាំខែ",
    "cln.input.payment_auto": "ស្វ័យប្រវត្តិ",
    "cln.override_reset": "កំណត់ស្វ័យប្រវត្តិ",
    "cln.result.payment": "ការទូទាត់ប្រចាំខែ",
    "cln.result.num_payments": "ចំនួនការទូទាត់",
    "cln.result.total_paid": "ចំនួនទឹកប្រាក់សរុបបានបង់",
    "cln.result.total_interest": "ការប្រាក់សរុបបានបង់",
    "cln.result.total_principal": "ប្រាក់ដើមសរុបបានបង់",
    "cln.result.final_date": "ថ្ងៃទូទាត់ចុងក្រោយ",
    "cln.hint.start_date": "ជម្រើស — ប្រើថ្ងៃនេះប្រសិនបើទទេ",
    "cln.hint.first_payment": "ជម្រើស — ស្វ័យប្រវត្តិ ១ ខែក្រោយថ្ងៃចាប់ផ្ដើម",
    "lcp.page_title": "ម៉ាស៊ីនគណនាប្រៀបធៀបប្រាក់កម្ចី",
    "lcp.page_desc": "ប្រៀបធៀបវិធីសងកម្ចីពីរ៖ ការបង់ប្រាក់ថេរប្រចាំខែ (ស្ដង់ដារ) ទល់នឹងការសងប្រាក់ដើមស្មើគ្នា ដើម្បីរកវិធីដែលចំណាយការប្រាក់សរុបតិចជាង។",
    "lcp.bread": "ប្រៀបធៀបប្រាក់កម្ចី",
    "lcp.print_title": "ម៉ាស៊ីនគណនាប្រៀបធៀបប្រាក់កម្ចី",
    "lcp.col.ep": "បង់ថេរ",
    "lcp.col.ep_desc": "ទឹកប្រាក់ថេរជារៀងរាល់ខែ",
    "lcp.col.epr": "បង់ថយ",
    "lcp.col.epr_desc": "ប្រាក់ដើមស្មើគ្នាជារៀងរាល់ខែ ការទូទាត់ថយចុះ",
    "lcp.result.monthly_payment": "ការទូទាត់ប្រចាំខែ",
    "lcp.result.first_payment": "ការទូទាត់លើកដំបូង",
    "lcp.result.last_payment": "ការទូទាត់ចុងក្រោយ",
    "lcp.result.total_paid": "ទឹកប្រាក់សរុបដែលបានបង់",
    "lcp.result.total_interest": "ការប្រាក់សរុបបានបង់",
    "lcp.result.num_payments": "ចំនួនការទូទាត់",
    "lcp.result.final_date": "កាលបរិច្ឆេទបង់ប្រាក់ចុងក្រោយ",
    "lcp.savings.saves": "សន្សំ",
    "lcp.savings.note_epr": "ការប្រាក់សរុប ធៀបនឹង បង់ថេរ",
    "lcp.savings.note_ep": "ការប្រាក់សរុប ធៀបនឹង បង់ថយ",
    "lcp.chart.title": "សមតុល្យប្រាក់កម្ចីតាមពេលវេលា",
    "lcp.chart.ep_balance": "បង់ថេរ — សមតុល្យ",
    "lcp.chart.epr_balance": "បង់ថយ — សមតុល្យ",
    "lcp.chart.ep_principal": "បង់ថេរ  — ប្រាក់ដើម",
    "lcp.chart.ep_interest": "បង់ថេរ  — ការប្រាក់",
    "lcp.chart.epr_principal": "បង់ថយ — ប្រាក់ដើម",
    "lcp.chart.epr_interest": "បង់ថយ — ការប្រាក់",
    "lcp.chart.view_balance": "សមតុល្យ",
    "lcp.chart.view_split": "ការបែងចែកការទូទាត់",
    "currency.khr_note": "អត្រាប្តូរប្រាក់: ៤,០០០ រៀល = ១ ដុល្លារ (ថេរ)",
    "cln.chart.title": "សមតុល្យប្រាក់កម្ចីតាមពេលវេលា",
    "cln.chart.balance": "សមតុល្យដែលនៅសល់",
    "cln.chart.cum_interest": "ការប្រាក់សរុប",
    "cln.sched.title": "កាលវិភាគសងប្រាក់",
    "cln.sched.num": "ការទូទាត់ #",
    "cln.sched.date": "កាលបរិច្ឆេត",
    "cln.sched.days": "ថ្ងៃ",
    "cln.sched.principal": "ប្រាក់ដើម",
    "cln.sched.interest": "ការប្រាក់",
    "cln.sched.payment": "ការទូទាត់",
    "cln.sched.balance": "សមតុល្យ",
    "cln.sched.totals": "សរុប",
    "print.note": "ចុចលើ <strong>បោះពុម្ភ / រក្សាទុកជា PDF</strong> ដើម្បីនាំចេញលទ្ធផល។ សូមប្រើប្រាស់ផ្ទាំងមុខងារបោះពុម្ពរបស់កម្មវិធីរុករក (Browser) របស់អ្នក រួចជ្រើសរើសយក \"រក្សាទុកជា PDF\" ជាទិសដៅសម្រាប់រក្សាទុកឯកសារ។",
    "print.btn": "បោះពុម្ភ / រក្សាទុកជា PDF",
    "print.date_prefix": "បោះពុម្ភរួចហើយ",
    "cmr.page_title": "ប្រាក់កម្ចីដើម-ប្រាក់ — អត្រាជាច្រើន",
    "cmr.page_desc": "បង្កើតកាលវិភាគសងប្រាក់ពេញលេញសម្រាប់ប្រាក់កម្ចីដែលមានអត្រាការប្រាក់ប្រែប្រួល។ តាមដានការទូទាត់ជាក់ស្ដែង និងគណនាពិន័យការទូទាត់យឺត។",
    "cmr.bread": "ប្រាក់កម្ចី — អត្រាជាច្រើន",
    "cmr.print_title": "ម័ស៊ឹនគណនាប្រាក់កម្ចី — អត្រាជាច្រើន",
    "cmr.section.periods": "វ័ណអត្រា",
    "cmr.period_label": "គ្រា {n}",
    "cmr.input.penalty_rate": "អត្រាពិន័យ (ប្រចាំឆ្នាំ)",
    "cmr.hint.penalty_rate": "អនុវត្តលើចំនួនមិនបានបង់នៅក្នុងម័ស៊ឹនគណនាពិន័យខាងក្រោម",
    "cmr.input.period_start": "ថ្ងៃចាប់ផ្ដើមគ្រា",
    "cmr.hint.period_start": "ថ្ងៃទូទាត់ដំបូងនៃអត្រាគ្រានេះ",
    "cmr.btn.add_period": "+ បន្ថែមគ្រាអត្រា",
    "cmr.btn.remove_period": "លុប",
    "cmr.error.period_date_required": "ថ្ងៃចាប់ផ្ដើមគ្រា {n} ត្រូវការ។",
    "cmr.error.period_date_order": "ថ្ងៃចាប់ផ្ដើមគ្រាត្រូវតែក្រោយថ្ងៃចាប់ផ្ដើមប្រាក់កម្ចី។",
    "cmr.error.first_date_order": "ថ្ងៃទូទាត់ដំបូងត្រូវតែក្រោយថ្ងៃចាប់ផ្ដើមប្រាក់កម្ចី។",
    "cmr.sched.status": "ស្ថានភាព",
    "cmr.sched.paid": "បានបង់",
    "cmr.sched.notes": "កំណត់ចំណាំ",
    "cmr.status.paid_full": "បង់ពេញ",
    "cmr.status.partial": "បង់មួយផ្នែក",
    "cmr.late.section": "ម័ស៊ឹនគណនាពិន័យការទូទាត់យឺត",
    "cmr.late.desc": "បញ្ចូលកាលបរិច្ឆេទដើម្បីមើលពិន័យលើការទូទាត់ដែលមិនទាន់បង់ ឬបង់មួយផ្នែក។",
    "cmr.late.as_of": "គណនារហូតដល់",
    "cmr.late.no_calc": "បញ្ចូលកាលបរិច្ឆេទ \"រហូតដល់\" ខាងលើដើម្បីគណនាពិន័យ។",
    "cmr.late.none": "រកឃើញការទូទាត់ហួសកំណត់គ្មានទេ។",
    "cmr.late.num": "#",
    "cmr.late.date_col": "ថ្ងៃដល់កំណត់",
    "cmr.late.days_col": "ថ្ងៃហួស",
    "cmr.late.installment": "ការដំឡើង",
    "cmr.late.paid_col": "បានបង់",
    "cmr.late.unpaid_col": "មិនទាន់បង់",
    "cmr.late.penalty_col": "ពិន័យ",
    "cmr.late.total_col": "សរុបហួសកំណត់",
    "cmr.late.total_row": "សរុប",
    "cmr.late.remaining_loan": "សមតុល្យប្រាក់កម្ចីដែលនៅសល់",
    "cmr.late.total_penalty": "ពិន័យសរុបបន្ថែម",
    "cmr.late.grand_total": "សរុបទឹកប្រាក់ដែលជំពាក់",
    "cinf.page_title": "ម៉ាស៊ឹនគណនាអតិផរណាកម្ពុជា",
    "cinf.desc": "មើលពីរបៀបដែលថាមពលទិញទំនិញប្ដូរប្រែតាមពេលវេលានៅកម្ពុជា ដោយប្រើទិន្នន័យ CPI ផ្លូវការពីវិទ្យាស្ថានជាតិស្ថិតិ។",
    "cinf.section.inputs": "ទិន្នន័យបញ្ចូល",
    "cinf.section.results": "លទ្ធផល",
    "cinf.input.amount": "ចំនួនទឹកប្រាក់",
    "cinf.input.from_date": "ពីខែ",
    "cinf.input.to_date": "ដល់ខែ",
    "cinf.note.source_label": "ប្រភពទិន្នន័យ:",
    "cinf.note.source": "វិទ្យាស្ថានជាតិស្ថិតិ (NIS), កម្ពុជា។ មូលដ្ឋាន CPI: តុលា–ធ្នូ ២០០៦ = ១០០។",
    "cinf.note.latest_label": "ទិន្នន័យចុងក្រោយ:",
    "cinf.placeholder": "បញ្ចូលចំនួនទឹកប្រាក់ និងជួរកាលបរិច្ឆេទខាងលើ។",
    "cinf.error.date_order": "ខែ \"ពី\" ត្រូវតែមុនខែ \"ដល់\"។",
    "cinf.result.hero_label": "ថាមពលទិញដែលសមមូល",
    "cinf.result.total_change": "អតិផរណាសរុប",
    "cinf.result.avg_annual": "អត្រាមធ្យមប្រចាំឆ្នាំ",
    "cinf.result.years": "រយៈពេល",
    "cinf.result.cpi_from": "CPI (ពី)",
    "cinf.result.cpi_to": "CPI (ដល់)",
    "cinf.result.interp_label": "ការបកស្រាយ:",
    "cinf.chart.power_title": "ថាមពលទិញតាមពេលវេលា",
    "cinf.chart.yoy_title": "អតិផរណាប្រចាំឆ្នាំ (ធ្នូ YoY %)",
    "cinf.table.title": "ទិន្នន័យ CPI ប្រចាំឆ្នាំ (ខែធ្នូ)",
    "cinf.table.year": "ឆ្នាំ",
    "cinf.table.cpi_index": "សន្ទស្សន៍ CPI (ធ្នូ)",
    "cinf.table.yoy": "ធ្នូ YoY %",
    "cinf.table.cum": "សម្បើមពីឆ្នាំ ២០០៤",
    "cinf.table.source_note": "ប្រភព: NIS កម្ពុជា។ មូលដ្ឋាន CPI តុលា–ធ្នូ ២០០៦ = ១០០។ YoY = ធ្នូ vs. ធ្នូមុន។",
    "cinf.print.note": "គណនាទាំងអស់ប្រើទិន្នន័យ CPI ផ្លូវការរបស់ NIS កម្ពុជា។ សម្រាប់គោលបំណងអប់រំតែប៉ុណ្ណោះ។",
    "cinf.print.btn": "បោះពុម្ព / រក្សាទុក PDF",
    "nssf.page_title": "ម៉ាស៊ឹនគណនាប្រាក់សោធននិវត្តន៍ បសស",
    "nssf.page_desc": "ប៉ាន់ប្រមាណប្រាក់សោធននិវត្តន៍ប្រចាំខែរបស់អ្នកពី បសស ដោយផ្អែកលើប្រាក់ខែ និងឆ្នាំរួមចំណែករបស់អ្នក។",
    "nssf.bread": "សោធននិវត្តន៍ បសស",
    "nssf.print_title": "ម៉ាស៊ឹនគណនាប្រាក់សោធននិវត្តន៍ បសស",
    "nssf.section.personal": "ព័ត៌មានលម្អិតផ្ទាល់ខ្លួន",
    "nssf.section.contribution": "វិភាគទាន បសស",
    "nssf.input.current_age": "អាយុបច្ចុប្បន្ន",
    "nssf.input.retirement_age": "អាយុចូលនិវត្តន៍",
    "nssf.hint.retirement_age": "បសស កម្ពុជា: អាយុចូលនិវត្តន៍ ៦០ ឆ្នាំ",
    "nssf.input.salary": "ប្រាក់ខែជាមធ្យម",
    "nssf.input.start_date": "ថ្ងៃចាប់ផ្ដើមរួមចំណែក",
    "nssf.hint.start_date": "ថ្ងៃដែលអ្នកចុះឈ្មោះ បសស ដំបូង",
    "nssf.result.monthly_pension": "ប្រាក់សោធនប្រចាំខែ",
    "nssf.result.annual_pension": "ប្រាក់សោធនប្រចាំឆ្នាំ",
    "nssf.result.total_years": "ឆ្នាំបង់វិភាគទានសរុប",
    "nssf.result.retirement_year": "ឆ្នាំចូលនិវត្តន៍",
    "nssf.result.pension_rate": "អត្រាសោធន",
    "nssf.result.as_pct_salary": "ប្រាក់សោធនជា % នៃប្រាក់ខែ",
    "nssf.result.formula": "រូបមន្តអត្រា:",
    "nssf.warn.under20": "ការរួមចំណែកតិចជាង ២០ ឆ្នាំ — អ្នកនឹងទទួលបានប្រាក់ជាដុំ ជំនួសឱ្យប្រាក់សោធនប្រចាំខែ។",
    "nssf.warn.zero_years": "ថ្ងៃចាប់ផ្ដើមរួមចំណែក នៅ ឬ ក្រោយការចូលនិវត្តន៍ — គ្មានប្រាក់សោធនបានកើតឡើង។",
    "nssf.chart.title": "ប្រាក់សោធនប្រចាំខែ តាមឆ្នាំរួមចំណែក",
    "nssf.chart.pension": "ប្រាក់សោធនប្រចាំខែ",
    "nssf.chart.you": "ករណីរបស់អ្នក",
    "nssf.table.title": "តារាងគណនាពេញ (ឆ្នាំ ១–៥០)",
    "nssf.table.year": "ឆ្នាំ",
    "nssf.table.formula": "រូបមន្ត",
    "nssf.table.rate": "អត្រា",
    "nssf.table.monthly": "ប្រាក់សោធនប្រចាំខែ",
    "nssf.table.annual": "ប្រាក់សោធនប្រចាំឆ្នាំ",
    "nssf.table.age": "អាយុពេលចូលនិវត្តន៍",
    "nssf.source": "ប្រភព: បសស កម្ពុជា។ អត្រា: ១.៧៥%/ឆ្នាំ (ឆ្នាំ ១–១៥); ១.២៥%/ឆ្នាំ (ឆ្នាំ ១៦+); អតិបរមា ៧០% នៅ ៥០ ឆ្នាំ។ ត្រូវការ ២០ ឆ្នាំ ដើម្បីបានប្រាក់សោធនប្រចាំខែ។",
    "dp.page_title": "យុត្ថសាស្ត្រសងបំណុល",
    "dti.page_title": "សមាមាត្របំណុលទៅប្រាក់ចំណូល (DTI)",
    "rvb.page_title": "ជួលផ្ទះ ធៀបនឹងបង់រំលស់ផ្ទះ​",
    "hvb.page_title": "សន្សំ៖ នៅផ្ទះ ធៀបនឹង ធនាគារ",
    "lp.input.annual_penalty_rate": "អត្រាការពិន័យប្រចាំឆ្នាំ (%)",
    "lp.result.daily_penalty_rate": "អត្រាការពិន័យប្រចាំថ្ងៃ (%)",
    "lp.input.due_date": "កាលបរិច្ឆេទត្រូវបង់",
    "lp.result.days_late": "ចំនួនថ្ងៃយឺត",
    "lp.result.overdue_amount": "ចំនួនប្រាក់ហួសកាលកំណត់",
    "lp.result.penalty_accrued": "ការពិន័យ",
    "lp.result.penalty_paid": "ការពិន័យបានបង់",
    "lp.result.interest_paid": "ការប្រាក់បានបង់",
    "lp.result.principal_paid": "ប្រាក់ដើមបានបង់",
    "lp.result.penalty_due": "ការពិន័យត្រូវបង់",
    "lp.result.interest_due": "ការប្រាក់ត្រូវបង់",
    "lp.result.principal_due": "ប្រាក់ដើមត្រូវបង់",
    "lp.result.total_due": "សរុបត្រូវបង់"
  }
};
