window.WFC_STRINGS = {
  "en": {
    "site.name": "Wise Financial Cambodia",
    "site.tagline": "Financial Education Tools",
    "site.footer.main": "Wise Financial Cambodia — Financial Education for the Kingdom of Cambodia",
    "site.footer.edu": "Calculators are for educational purposes. Consult a financial advisor for personal advice.",
    "site.footer.edu_short": "Calculators are for educational purposes only.",
    "nav.all": "All Calculators",
    "nav.savings": "Savings",
    "nav.loans": "Loans",
    "nav.budgeting": "Budgeting",
    "nav.fixed": "Fixed Savings",
    "nav.monthly": "Monthly Savings",
    "nav.loan": "Loan Calculator",
    "bread.calculators": "Calculators",
    "bread.savings": "Savings",
    "bread.loans": "Loans",
    "index.title": "Financial Calculators",
    "index.desc": "Free, easy-to-use tools to help you plan your savings, understand loans, and make wise financial decisions. All calculations happen right in your browser.",
    "index.savings_col": "💰 Savings Calculators",
    "index.loans_col": "🏦 Loan Calculators",
    "index.budget_col": "📊 Budgeting Calculators",
    "badge.live": "Live",
    "badge.soon": "Soon",
    "calc.fixed.name": "Fixed Deposit Savings",
    "calc.fixed.desc": "Grow a lump-sum deposit at compound interest over time",
    "calc.monthly.name": "Monthly Contribution Savings",
    "calc.monthly.desc": "See how regular monthly deposits build up your balance",
    "calc.emergency.name": "Emergency Fund",
    "calc.emergency.desc": "Estimate how much to save for emergencies based on your expenses",
    "calc.nssf.name": "NSSF Pension",
    "calc.nssf.desc": "Approximate your future balance with Cambodia’s NSSF program",
    "calc.retire.name": "Retirement Future Balance",
    "calc.retire.desc": "Calculate future balance of your personal retirement plan",
    "calc.homevsbank.name": "Savings: Home vs. Bank",
    "calc.homevsbank.desc": "Compare early and late savers keeping money at home vs. the bank",
    "calc.invest.name": "Investment Evaluation",
    "calc.invest.desc": "Assess whether an investment is giving a healthy return",
    "calc.simple_daily.name": "Simple Interest – Daily",
    "calc.simple_daily.desc": "Calculate daily loan interest; find unknown interest rate",
    "calc.simple_monthly.name": "Simple Interest – Monthly/Yearly",
    "calc.simple_monthly.desc": "Monthly or yearly simple interest; find unknown interest rate",
    "calc.loan4.name": "Loan Calculator (4 Parts)",
    "calc.loan4.desc": "Solve for any missing piece of a loan (principal, rate, term, payment)",
    "calc.compound_loan.name": "Compound Interest Loan",
    "calc.compound_loan.desc": "Full amortisation schedule with holiday-aware payment dates and overrides",
    "calc.loan_flexible.name": "Flexible Loan (Periodic Principal)",
    "calc.loan_flexible.desc": "Interest charged monthly, principal repaid in larger periodic lump sums",
    "calc.loan_multi_rate.name": "Compound Loan — Multiple Rates",
    "calc.loan_multi_rate.desc": "Loan with changing interest rate periods; includes late fee / overdue penalty calculator",
    "calc.loan_adjusted.name": "Loan Restructure Comparison",
    "calc.loan_adjusted.desc": "Side-by-side: current loan terms vs. proposed restructure — models underpayment and rate changes",
    "calc.loan_comp.name": "Loan Comparison",
    "calc.loan_comp.desc": "Equal payment vs. equal principal payment side-by-side",
    "calc.promo.name": "Promotional Loan",
    "calc.promo.desc": "Loans with different interest rate periods",
    "calc.cambodia_loans.name": "Comparing Cambodian Loans",
    "calc.cambodia_loans.desc": "Compare all common debt types available in Cambodia",
    "calc.credit_card.name": "Credit Card Debt",
    "calc.credit_card.desc": "Understand the true cost of credit card balances",
    "calc.debt_payoff.name": "Debt Pay-Off Strategies",
    "calc.debt_payoff.desc": "Find the best path to pay off multiple loans",
    "calc.dti.name": "DTI – Debt to Income Ratio",
    "calc.dti.desc": "Determine your ability to take on housing and other debt",
    "calc.rent_vs_buy.name": "Renting vs. Financing",
    "calc.rent_vs_buy.desc": "Is it more economical to rent or finance a home?",
    "calc.family_budget.name": "Family Budget",
    "calc.family_budget.desc": "Basic budget planning for a family",
    "calc.church_budget.name": "Church Budget",
    "calc.church_budget.desc": "Simple tool for making church budgets",
    "calc.farm_budget.name": "Farming Budget",
    "calc.farm_budget.desc": "Calculate whether a crop is profitable",
    "calc.insurance.name": "Insurance – End Early?",
    "calc.insurance.desc": "Evaluate whether cancelling an insurance policy is a good idea",
    "calc.inflation.name": "Cambodian Inflation Calculator",
    "calc.inflation.desc": "What is a fixed amount of money worth in today’s terms?",
    "input.label": "Inputs",
    "input.main": "Main Inputs",
    "input.optional": "Optional Settings",
    "input.annual_rate": "Annual Interest Rate",
    "input.time_period": "Time Period",
    "input.unit": "Unit",
    "input.years": "Years",
    "input.months": "Months",
    "input.comp_freq": "Compounding Frequency",
    "input.freq.monthly": "Monthly",
    "input.freq.quarterly": "Quarterly",
    "input.freq.semi": "Semi-Annual",
    "input.freq.annual": "Annual",
    "input.freq.daily": "Daily",
    "input.nationality": "Depositor Type",
    "input.nat.national": "Cambodian National (6% tax)",
    "input.nat.foreigner": "Foreigner (12% tax)",
    "input.days_unit": "days",
    "btn.calculate": "Calculate",
    "result.summary": "Summary Results",
    "result.effective_rate": "Effective Annual Yield",
    "result.rule72": "Years to Double (Rule of 72)",
    "result.quick_cmp": "Quick Comparison",
    "cmp.scenario": "Scenario",
    "cmp.future_value": "Future Value",
    "cmp.current": "▶ Current Plan",
    "cmp.plus1": "If rate were +1%",
    "cmp.minus1": "If rate were −1%",
    "cmp.double_time": "Double the time",
    "fixed.page_title": "Fixed Deposit Savings Calculator",
    "fixed.page_desc": "See how a one-time deposit grows with compound interest over time.",
    "fixed.bread": "Fixed Deposit Savings Calculator",
    "fixed.print_title": "Fixed Deposit Savings Calculator",
    "fixed.input.principal": "Initial Deposit",
    "fixed.result.future_value_net": "After-Tax Future Value",
    "fixed.result.principal": "Initial Deposit",
    "fixed.result.gross_interest": "Gross Interest Earned",
    "fixed.result.tax_deducted": "Tax Deducted",
    "fixed.result.net_interest": "Net Interest (after tax)",
    "fixed.chart.title": "Savings Growth Chart",
    "fixed.chart.net_balance": "After-Tax Balance",
    "fixed.chart.gross_balance": "Gross Balance (before tax)",
    "fixed.chart.principal": "Principal",
    "cmp.fixed.half": "If deposit were half",
    "cmp.fixed.double": "If deposit were double",
    "simple_monthly.page_title": "Simple Interest – Monthly/Yearly Repayment Calculator",
    "simple_monthly.page_desc": "Calculate interest and repayment schedules for simple-interest loans. Choose whether interest is charged monthly or yearly, and whether it is based on the original or remaining balance. Optionally set a higher payment to start reducing the principal.",
    "simple_monthly.bread": "Simple Interest – Monthly/Yearly",
    "simple_monthly.print_title": "Simple Interest – Monthly/Yearly Repayment Calculator",
    "simple_monthly.card.payment": "Payment Settings",
    "simple_monthly.input.rate": "Interest Rate",
    "simple_monthly.input.rate_period": "Rate Period",
    "simple_monthly.input.period.monthly": "Per Month",
    "simple_monthly.input.period.yearly": "Per Year",
    "simple_monthly.input.interest_base": "Calculate Interest On",
    "simple_monthly.input.base.original": "Original Principal",
    "simple_monthly.input.base.remaining": "Remaining Balance",
    "simple_monthly.input.principal_label": "Principal Reduction (optional)",
    "simple_monthly.input.principal_hint": "Set a monthly payment above the interest amount to start paying off the principal.",
    "simple_monthly.input.new_payment": "Monthly Payment",
    "simple_monthly.input.new_payment_date": "Payment Start Date (optional)",
    "simple_monthly.result.total_repaid": "Total Amount Repaid",
    "simple_monthly.result.interest_only": "Monthly Interest Payment",
    "simple_monthly.result.never_paid": "No end date",
    "simple_monthly.result.never_paid_hint": "Loan is never paid off — set a payment above the interest to repay principal",
    "simple_monthly.result.total_interest": "Total Interest Paid",
    "simple_monthly.result.monthly_interest": "Monthly Interest",
    "simple_monthly.result.yearly_interest": "Annual Interest",
    "simple_monthly.result.term": "Loan Term",
    "simple_monthly.result.months": "months",
    "simple_monthly.result.partial": "partial",
    "simple_monthly.per_month": "/mo",
    "simple_monthly.per_year": "/yr",
    "simple_monthly.chart.title": "Remaining Balance Over Time",
    "simple_monthly.chart.balance": "Remaining Balance",
    "simple_monthly.sched.month": "Month",
    "simple_monthly.sched.interest": "Interest",
    "simple_monthly.sched.payment": "Payment",
    "simple_monthly.sched.principal_paid": "Principal Paid",
    "simple_monthly.sched.never_paid_note": "This pattern continues indefinitely. Set a monthly payment above the interest amount to pay off the loan.",
    "simple_daily.page_title": "Simple Interest Daily Repayment Calculator",
    "simple_daily.page_desc": "Enter the loan amount and total payback amount to see the daily payment schedule and true annual interest rate for up to three repayment term options.",
    "simple_daily.bread": "Simple Interest – Daily",
    "simple_daily.print_title": "Simple Interest Daily Repayment Calculator",
    "simple_daily.input.currency": "Currency",
    "simple_daily.input.loan": "Loan Amount (Principal)",
    "simple_daily.input.payback": "Payback Amount (Total to Repay)",
    "simple_daily.input.start_date": "Loan Start Date (optional)",
    "simple_daily.input.options_label": "Repayment Term Options",
    "simple_daily.input.opt1": "Option 1",
    "simple_daily.input.opt2": "Option 2",
    "simple_daily.input.opt3": "Option 3",
    "simple_daily.result.total_interest": "Total Interest (Lender Profit)",
    "simple_daily.result.loan_amount": "Loan Amount",
    "simple_daily.result.payback_amount": "Payback Amount",
    "simple_daily.result.comparison": "Option Comparison",
    "simple_daily.result.option_col": "Option",
    "simple_daily.result.days_col": "Days",
    "simple_daily.result.daily_pmt_col": "Daily Payment",
    "simple_daily.result.annual_rate_col": "Annual Rate",
    "simple_daily.chart.title": "Daily Remaining Balance",
    "simple_daily.chart.opt1": "Option 1",
    "simple_daily.chart.opt2": "Option 2",
    "simple_daily.chart.opt3": "Option 3",
    "simple_daily.sched.day": "Day",
    "simple_daily.sched.date": "Date",
    "monthly.page_title": "Monthly Contribution Savings Calculator",
    "monthly.page_desc": "See how regular monthly deposits — with or without an initial lump sum — grow over time.",
    "monthly.bread": "Monthly Contribution Savings Calculator",
    "monthly.print_title": "Monthly Contribution Savings Calculator",
    "monthly.input.contrib": "Monthly Contribution",
    "monthly.input.principal": "Initial Deposit (optional)",
    "monthly.input.timing": "Contribution Timing",
    "monthly.timing.end": "End of Period",
    "monthly.timing.begin": "Beginning of Period",
    "monthly.result.future_value": "Future Value",
    "monthly.result.future_value_net": "After-Tax Future Value",
    "monthly.result.principal": "Initial Deposit",
    "monthly.result.total_contribs": "Total Contributions",
    "monthly.result.total_principal": "Total Principal Invested",
    "monthly.result.total_interest": "Total Interest Earned",
    "monthly.result.gross_interest": "Gross Interest Earned",
    "monthly.result.tax_deducted": "Tax Deducted",
    "monthly.result.net_interest": "Net Interest (after tax)",
    "monthly.chart.title": "Savings Growth Chart",
    "monthly.chart.balance": "After-Tax Balance",
    "monthly.chart.gross_balance": "Gross Balance (before tax)",
    "monthly.chart.invested": "Total Invested",
    "cmp.monthly.lump_only": "Lump sum only (no monthly)",
    "cmp.monthly.month_only": "Monthly only (no lump sum)",
    "loan.page_title": "Loan Calculator (4 Parts)",
    "loan.page_desc": "Know any 3 loan variables? Solve for the missing one — payment, principal, interest rate, or loan term.",
    "loan.bread": "Loan Calculator (4 Parts)",
    "loan.print_title": "Loan Calculator (4 Parts)",
    "loan.section.currency": "Currency",
    "loan.exrate": "Exchange Rate (1 USD =)",
    "loan.section.solve": "Solve For",
    "loan.solve.payment": "Monthly\nPayment",
    "loan.solve.principal": "Loan\nAmount",
    "loan.solve.rate": "Interest\nRate",
    "loan.solve.nper": "Loan\nTerm",
    "loan.section.details": "Loan Details",
    "loan.input.principal": "Loan Amount",
    "loan.input.rate": "Annual Interest Rate",
    "loan.input.term": "Loan Term",
    "loan.input.payment": "Monthly Payment",
    "loan.result.principal": "Loan Amount",
    "loan.result.payment": "Monthly Payment",
    "loan.result.total_paid": "Total Amount Paid",
    "loan.result.total_interest": "Total Interest Paid",
    "loan.result.interest_pct": "Interest as % of Principal",
    "loan.result.term": "Loan Term",
    "loan.hero.payment": "Monthly Payment",
    "loan.hero.principal": "Loan Amount",
    "loan.hero.rate": "Annual Interest Rate",
    "loan.hero.nper": "Loan Term",
    "loan.chart.title": "Loan Balance Over Time",
    "loan.chart.balance": "Remaining Balance",
    "loan.chart.cum_interest": "Cumulative Interest Paid",
    "loan.schedule.title": "Amortization Schedule",
    "loan.sched.payment_num": "Payment #",
    "loan.sched.payment": "Payment",
    "loan.sched.principal": "Principal",
    "loan.sched.remaining": "Remaining Balance",
    "cmp.loan.header.pmt": "Monthly Pmt",
    "cmp.loan.header.int": "Total Interest",
    "cmp.loan.plus1": "Rate +1%",
    "cmp.loan.minus1": "Rate −1%",
    "cmp.loan.1yr": "1-year term",
    "cmp.loan.3yr": "3-year term",
    "schedule.title": "Period-by-Period Schedule",
    "schedule.show": "Show Schedule",
    "schedule.hide": "Hide Schedule",
    "sched.period": "Period",
    "sched.date": "Date",
    "sched.beg_balance": "Beg. Balance",
    "sched.interest": "Interest Earned",
    "sched.gross_interest": "Gross Interest",
    "sched.tax": "Tax",
    "sched.net_interest": "Net Interest",
    "sched.end_balance": "End Balance",
    "sched.cum_interest": "Cumulative Interest",
    "sched.cum_net_interest": "Cum. Net Interest",
    "sched.cum_contribs": "Cum. Contributions",
    "fl.page_title": "Flexible Loan — Periodic Principal",
    "fl.page_desc": "Interest is charged monthly on the outstanding balance. Principal is repaid in periodic lump sums every N months. Generates a full date-based amortisation schedule with holiday-aware payment dates.",
    "fl.bread": "Flexible Loan",
    "fl.print_title": "Flexible Loan Calculator",
    "fl.section.loan": "Loan Details",
    "fl.section.dates": "Dates",
    "fl.section.settings": "Settings",
    "fl.section.structure": "Payment Structure",
    "fl.input.loan_amount": "Loan Amount",
    "fl.input.rate": "Annual Interest Rate",
    "fl.input.term": "Loan Term",
    "fl.input.start_date": "Loan Start Date",
    "fl.input.override_date": "Override Start Date",
    "fl.input.override_hint": "Optional – overrides the reference date for the first period's day count only",
    "fl.input.first_payment": "First Payment Date",
    "fl.input.day_count": "Day Count Method",
    "fl.day_count.standard": "Standard – Actual days / 360",
    "fl.day_count.actual": "Actual – Actual days / 365",
    "fl.input.delay_rule": "Payment Date Rule",
    "fl.delay.none": "No adjustment",
    "fl.delay.skip_sun": "Skip Sunday",
    "fl.delay.skip_sat_sun": "Skip Saturday & Sunday",
    "fl.delay.skip_sun_hol": "Skip Sunday & Holidays",
    "fl.delay.skip_all": "Skip Sat, Sun & Holidays",
    "fl.input.frequency": "Principal Payment Frequency",
    "fl.input.frequency_unit": "months",
    "fl.input.freq_start": "Frequency Start Date",
    "fl.input.fixed_principal": "Fixed Principal / Payment",
    "fl.principal.auto": "auto",
    "fl.principal.reset": "reset to auto",
    "fl.input.defer": "Defer Interest to Payment",
    "fl.defer.no": "No – pay interest monthly",
    "fl.defer.yes": "Yes – accumulate, pay with principal",
    "fl.result.monthly_interest": "Typical Monthly Interest",
    "fl.result.lump_sum": "Principal Lump Sum",
    "fl.result.total_paid": "Total Amount Paid",
    "fl.result.total_principal": "Total Principal",
    "fl.result.total_interest": "Total Interest",
    "fl.result.maturity": "Maturity Date",
    "fl.chart.title": "Loan Balance Over Time",
    "fl.chart.balance": "Remaining Balance",
    "fl.chart.cum_interest": "Cumulative Interest",
    "fl.sched.title": "Amortisation Schedule",
    "fl.sched.num": "No.",
    "fl.sched.date": "Payment Date",
    "fl.sched.days": "Days",
    "fl.sched.principal": "Principal",
    "fl.sched.interest": "Interest",
    "fl.sched.total": "Total",
    "fl.sched.balance": "Balance",
    "fl.sched.totals": "Totals",
    "ef.page_title": "Emergency Fund Calculator",
    "ef.page_desc": "Enter your monthly expenses to find out how much you need in an emergency fund. Experts recommend saving 3-6 months of living expenses.",
    "ef.bread": "Emergency Fund",
    "ef.print_title": "Emergency Fund Calculator",
    "ef.section.expenses": "Monthly Expenses",
    "ef.col.amount": "Amount",
    "ef.input.housing": "Housing (Rent, Utilities)",
    "ef.input.food": "Food",
    "ef.input.transport": "Transportation",
    "ef.input.debt": "Debt Payments",
    "ef.input.education": "Child Education",
    "ef.input.phone": "Phone",
    "ef.input.insurance": "Insurance",
    "ef.input.property_tax": "Property Tax",
    "ef.input.other": "Other",
    "ef.total": "Total Monthly Expenses",
    "ef.goals.title": "Emergency Fund Goals",
    "ef.level.basic_dot": "Basic",
    "ef.level.good_dot": "Good",
    "ef.level.better_dot": "Better",
    "ef.level.basic_desc": "1 month of expenses",
    "ef.level.good_desc": "3 months of expenses",
    "ef.level.better_desc": "6 months of expenses",
    "ef.goal.basic": "1 Month - Basic",
    "ef.goal.basic_sub": "Minimum recommended",
    "ef.goal.good": "3 Months - Good",
    "ef.goal.good_sub": "Standard recommendation",
    "ef.goal.better": "6 Months - Better",
    "ef.goal.better_sub": "Best practice",
    "ef.chart.title": "Emergency Fund Goals",
    "cln.page_title": "Compound Interest Loan",
    "cln.page_desc": "Build a full date-based amortisation schedule for a compound interest loan. Choose 30/360 or Actual/360 day count, with automatic adjustment for Sundays and Cambodian public holidays.",
    "cln.bread": "Compound Interest Loan",
    "cln.print_title": "Compound Interest Loan Calculator",
    "cln.input.loan_amount": "Loan Amount",
    "cln.input.rate": "Annual Interest Rate",
    "cln.input.term": "Loan Term",
    "cln.input.start_date": "Loan Start Date",
    "cln.input.first_payment": "First Payment Date",
    "cln.input.day_count": "Day Count Method",
    "cln.day_count.30_360": "30/360 (rate ÷ 12 per period)",
    "cln.day_count.actual_360": "Actual/360 (rate ÷ 360 × actual days)",
    "cln.input.delay_rule": "Payment Date Rule",
    "cln.delay.none": "No adjustment",
    "cln.delay.skip_sun": "Skip Sunday → Monday",
    "cln.delay.skip_sun_hol": "Skip Sunday & Cambodian Holidays",
    "cln.delay.skip_sat_sun": "Skip Saturday & Sunday → Monday",
    "cln.delay.skip_sat_sun_hol": "Skip Sat, Sun & Cambodian Holidays",
    "cln.input.payment": "Monthly Payment",
    "cln.input.payment_auto": "auto",
    "cln.override_reset": "reset to auto",
    "cln.result.payment": "Monthly Payment",
    "cln.result.num_payments": "Number of Payments",
    "cln.result.total_paid": "Total Amount Paid",
    "cln.result.total_interest": "Total Interest Paid",
    "cln.result.total_principal": "Total Principal Paid",
    "cln.result.final_date": "Final Payment Date",
    "cln.hint.start_date": "Optional — defaults to today",
    "cln.hint.first_payment": "Optional — auto-set to 1 month after start",
    "lcp.page_title": "Loan Comparison Calculator",
    "lcp.page_desc": "Compare equal payment (standard amortisation) with equal principal repayment side by side. See which method costs less in total interest.",
    "lcp.bread": "Loan Comparison",
    "lcp.print_title": "Loan Comparison Calculator",
    "lcp.col.ep": "Equal Payment",
    "lcp.col.ep_desc": "Fixed amount every month",
    "lcp.col.epr": "Equal Principal",
    "lcp.col.epr_desc": "Same principal every month; payments decrease",
    "lcp.result.monthly_payment": "Monthly Payment",
    "lcp.result.first_payment": "First Payment",
    "lcp.result.last_payment": "Last Payment",
    "lcp.result.total_paid": "Total Amount Paid",
    "lcp.result.total_interest": "Total Interest Paid",
    "lcp.result.num_payments": "Number of Payments",
    "lcp.result.final_date": "Final Payment Date",
    "lcp.savings.saves": "saves",
    "lcp.savings.note_epr": "in total interest vs. Equal Payment",
    "lcp.savings.note_ep": "in total interest vs. Equal Principal",
    "lcp.chart.title": "Loan Balance Over Time",
    "lcp.chart.ep_balance": "Equal Payment — Balance",
    "lcp.chart.epr_balance": "Equal Principal — Balance",
    "lcp.chart.ep_principal": "Equal Payment — Principal",
    "lcp.chart.ep_interest": "Equal Payment — Interest",
    "lcp.chart.epr_principal": "Equal Principal — Principal",
    "lcp.chart.epr_interest": "Equal Principal — Interest",
    "lcp.chart.view_balance": "Balance",
    "lcp.chart.view_split": "Payment Split",
    "currency.khr_note": "Exchange rate: 4,000 KHR = 1 USD (fixed)",
    "cln.chart.title": "Loan Balance Over Time",
    "cln.chart.balance": "Remaining Balance",
    "cln.chart.cum_interest": "Cumulative Interest",
    "cln.sched.title": "Amortisation Schedule",
    "cln.sched.num": "Payment #",
    "cln.sched.date": "Date",
    "cln.sched.days": "Days",
    "cln.sched.principal": "Principal",
    "cln.sched.interest": "Interest",
    "cln.sched.payment": "Payment",
    "cln.sched.balance": "Balance",
    "cln.sched.totals": "Totals",
    "print.note": "Click <strong>Print / Save as PDF</strong> to export results. Use your browser’s print dialog and choose \"Save as PDF\" as the destination.",
    "print.btn": "Print / Save as PDF",
    "print.date_prefix": "printed",
    "cmr.page_title": "Compound Loan — Multiple Rates",
    "cmr.page_desc": "Build a full amortisation schedule for a loan with changing interest rate periods. Track actual payments and calculate overdue penalty fees.",
    "cmr.bread": "Compound Loan — Multiple Rates",
    "cmr.print_title": "Compound Loan — Multiple Rates Calculator",
    "cmr.section.periods": "Rate Periods",
    "cmr.period_label": "Period {n}",
    "cmr.input.penalty_rate": "Penalty Rate (Annual)",
    "cmr.hint.penalty_rate": "Applied to unpaid amounts in the overdue calculator below",
    "cmr.input.period_start": "Period Start Date",
    "cmr.hint.period_start": "First payment date of this rate period",
    "cmr.btn.add_period": "+ Add Rate Period",
    "cmr.btn.remove_period": "Remove",
    "cmr.error.period_date_required": "Period {n} start date is required.",
    "cmr.error.period_date_order": "Period start dates must be after the loan start date.",
    "cmr.error.first_date_order": "First payment date must be after the loan start date.",
    "cmr.sched.status": "Status",
    "cmr.sched.paid": "Paid",
    "cmr.sched.notes": "Notes",
    "cmr.status.paid_full": "Paid Full",
    "cmr.status.partial": "Partial Paid",
    "cmr.late.section": "Overdue Penalty Calculator",
    "cmr.late.desc": "Enter a date to see penalty fees on all unpaid or partially paid instalments.",
    "cmr.late.as_of": "Calculate As Of",
    "cmr.late.no_calc": "Enter an \"As Of\" date above to calculate overdue penalties.",
    "cmr.late.none": "No overdue payments found as of this date.",
    "cmr.late.num": "#",
    "cmr.late.date_col": "Due Date",
    "cmr.late.days_col": "Days Overdue",
    "cmr.late.installment": "Installment",
    "cmr.late.paid_col": "Paid",
    "cmr.late.unpaid_col": "Unpaid",
    "cmr.late.penalty_col": "Penalty",
    "cmr.late.total_col": "Total Overdue",
    "cmr.late.total_row": "Total",
    "cmr.late.remaining_loan": "Remaining Loan Balance",
    "cmr.late.total_penalty": "Total Penalty Added",
    "cmr.late.grand_total": "Grand Total Owing",
    "cinf.page_title": "Cambodian Inflation Calculator",
    "cinf.desc": "See how the purchasing power of money has changed over time in Cambodia using official CPI data from the National Institute of Statistics.",
    "cinf.section.inputs": "Inputs",
    "cinf.section.results": "Results",
    "cinf.input.amount": "Amount",
    "cinf.input.from_date": "From Month",
    "cinf.input.to_date": "To Month",
    "cinf.note.source_label": "Data source:",
    "cinf.note.source": "National Institute of Statistics (NIS), Cambodia. CPI base: Oct–Dec 2006 = 100.",
    "cinf.note.latest_label": "Latest data:",
    "cinf.placeholder": "Enter an amount and date range above.",
    "cinf.error.date_order": "\"From\" month must be before \"To\" month.",
    "cinf.result.hero_label": "Equivalent Purchasing Power",
    "cinf.result.total_change": "Total Inflation",
    "cinf.result.avg_annual": "Avg. Annual Rate",
    "cinf.result.years": "Period",
    "cinf.result.cpi_from": "CPI (From)",
    "cinf.result.cpi_to": "CPI (To)",
    "cinf.result.interp_label": "Interpretation:",
    "cinf.chart.power_title": "Purchasing Power Over Time",
    "cinf.chart.yoy_title": "Annual Inflation (Dec YoY %)",
    "cinf.table.title": "Annual CPI Data (December)",
    "cinf.table.year": "Year",
    "cinf.table.cpi_index": "CPI Index (Dec)",
    "cinf.table.yoy": "Dec YoY %",
    "cinf.table.cum": "Cumulative from 2004",
    "cinf.table.source_note": "Source: NIS Cambodia. CPI base Oct–Dec 2006 = 100. YoY = December vs. previous December.",
    "cinf.print.note": "All calculations use official NIS Cambodia CPI data. For educational purposes only.",
    "cinf.print.btn": "Print / Save PDF",
    "nssf.page_title": "NSSF Pension Calculator",
    "nssf.page_desc": "Estimate your monthly pension from Cambodia's National Social Security Fund based on your salary and years of contribution.",
    "nssf.bread": "NSSF Pension",
    "nssf.print_title": "NSSF Pension Calculator",
    "nssf.section.personal": "Personal Details",
    "nssf.section.contribution": "NSSF Contribution",
    "nssf.input.current_age": "Current Age",
    "nssf.input.retirement_age": "Retirement Age",
    "nssf.hint.retirement_age": "Cambodia NSSF retirement age: 60",
    "nssf.input.salary": "Average Monthly Salary",
    "nssf.input.start_date": "Contribution Start Date",
    "nssf.hint.start_date": "Date you first enrolled in NSSF",
    "nssf.result.monthly_pension": "Monthly Pension",
    "nssf.result.annual_pension": "Annual Pension",
    "nssf.result.total_years": "Total Contribution Years",
    "nssf.result.retirement_year": "Retirement Year",
    "nssf.result.pension_rate": "Pension Rate",
    "nssf.result.as_pct_salary": "Pension as % of Salary",
    "nssf.result.formula": "Rate Formula:",
    "nssf.warn.under20": "Less than 20 years of contribution — you will receive a lump sum instead of a monthly pension.",
    "nssf.warn.zero_years": "Contribution start date is at or after retirement — no pension accrued.",
    "nssf.chart.title": "Monthly Pension by Years of Contribution",
    "nssf.chart.pension": "Monthly Pension",
    "nssf.chart.you": "Your scenario",
    "nssf.table.title": "Full Calculation Table (Years 1–50)",
    "nssf.table.year": "Year",
    "nssf.table.formula": "Formula",
    "nssf.table.rate": "Rate",
    "nssf.table.monthly": "Monthly Pension",
    "nssf.table.annual": "Annual Pension",
    "nssf.table.age": "Age at Retirement",
    "nssf.source": "Source: Cambodia NSSF. Rate: 1.75%/yr (years 1–15); 1.25%/yr (year 16+); max 70% at 50 years. Minimum 20 years required for monthly pension.",
    "dp.page_title": "Debt Pay-Off Strategies",
    "dti.page_title": "DTI – Debt to Income Ratio",
    "rvb.page_title": "Renting vs. Financing",
    "hvb.page_title": "Savings: Home vs. Bank"
  },
  "km": {
    "site.name": "ហិរញ្ញវត្ថុឆ្លាតវៃ កម្ពុជា",
    "site.tagline": "ឧបករណ៍អប់រំហិរញ្ញវត្ថុ",
    "site.footer.main": "ហិរញ្ញវត្ថុឆ្លាតវៃ កម្ពុជា — អប់រំហិរញ្ញវត្ថុសម្រាប់ព្រះរាជាណាចក្រកម្ពុជា។",
    "site.footer.edu": "ម៉ាស៊ីនគណនាសម្រាប់គោលបំណងអប់រំ។ ជួយជាយោបល់ដល់អ្នកប្រឹក្សាហិរញ្ញវត្ថុសម្រាប់​ជាដំបូលន្មានផ្ទាល់ខ្លួន។",
    "site.footer.edu_short": "ម៉ាស៊ីនគណនាសម្រាប់តែគោលបំណងអប់រំប៉ុណ្ណោះ។",
    "nav.all": "ម៉ាស៊ីនគណនាទាំងអស់",
    "nav.savings": "ការសន្សាំ",
    "nav.loans": "ប្រាកកម្ចឹ",
    "nav.budgeting": "ថវិកា",
    "nav.fixed": "ការសន្សំមានកាលកំណត់",
    "nav.monthly": "ការសន្សំប្រចាំខែ",
    "nav.loan": "ម៉ាស៊ីនគណនាឥណទាន",
    "bread.calculators": "ម៉ាស៊ីនគណនា",
    "bread.savings": "ការសន្សំ",
    "bread.loans": "ឥណទាន",
    "index.title": "ម៉ាស៊ីនគណនាហិរញ្ញវត្ថុ",
    "index.desc": "ប្រើប្រាស់ដោយឥតគិតថ្លៃ ឧបករណ៍ងាយស្រួលប្រើប្រាស់ ដើម្បីជួយអ្នករៀបចំផែនការសន្សំ យល់ដឹងអំពីឥណទាន និងធ្វើការសម្រេចចិត្តហិរញ្ញវត្ថុប្រកបដោយប្រាជ្ញា។ ម៉ាស៊ីនគណនាទាំងនៅខាងស្តាំក្នុងកម្មវិធីរុករករបស់អ្នក",
    "index.savings_col": "💰 ម៉ាស៊ីនគណនាការសន្សំ",
    "index.loans_col": "🏦 ម៉ាស៊ីនគណនាឥណទាន",
    "index.budget_col": "📊 ម៉ាស៊ីនគណនាថវិការ",
    "badge.live": "ដាក់បង្ហាញ",
    "badge.soon": "ឆាប់ៗ",
    "calc.fixed.name": "ការដាក់ប្រាក់បញ្ញើសន្សំមានរយៈពេលកំណត់",
    "calc.fixed.desc": "បង្កើនទឹកប្រាក់បញ្ញើសន្សំដែលដាក់តែម្តងឱ្យកើនឡើងតាមពេលវេលា ដោយទទួលបានការប្រាក់សមាស។",
    "calc.monthly.name": "ការដាក់ប្រាក់បញ្ញើសន្សំប្រចាំខែ",
    "calc.monthly.desc": "មើលពីរបៀបដាក់ប្រាក់បញ្ញើសន្សំជាទៀងទាត់ដើម្បីកសាងសមតុល្យទឹកប្រាក់របស់អ្នក",
    "calc.emergency.name": "មូលនិធិគ្រាអាសន្ន",
    "calc.emergency.desc": "ការប៉ាន់ប្រមាណត្រូវធ្វើការសន្សំប៉ុន្មានសម្រាប់គ្រាអាសន្នដោយផ្អែកលើការចំណាយរបស់អ្នក។",
    "calc.nssf.name": "មូលនិធិសោធននិវត្សរ៍ ប.ស.ស",
    "calc.nssf.desc": "ប៉ាន់ស្មានសមតុល្យប្រាក់នាពេលអនាគតរបស់អ្នកតាមកម្មវិធី ប.ស.ស. របស់កម្ពុជា។",
    "calc.retire.name": "សមតុល្យទឹកប្រាក់ចូលនិវត្សន៍អនាគត",
    "calc.retire.desc": "គណនាសមតុល្យទឹកប្រាក់អនាគតនៃផែនការចូលនិវត្សន៍ផ្ទាល់ខ្លួនរបស\nអ្នក",
    "calc.homevsbank.name": "សន្សាំ៖ ផ្តែហ ៤ ធនាគារ",
    "calc.homevsbank.desc": "ប្រើបធ្រឹប្រាកនៅផ្តែហ ៤ ធនាគារសម្រាបអ្នកសន្សាំដុម និងក្រោយ",
    "calc.invest.name": "វាយតម្លការវិនិយឹគ",
    "calc.invest.desc": "វាយតម្លថាតើលការវិនិយឹគមួយផ្តល់នៅកុលដឹល់អាចការប្រាកល័ឡ៤ត់អត់",
    "calc.simple_daily.name": "ការប្រាកសាមញ្ញ – ប្រចាំថ្ងៃ",
    "calc.simple_daily.desc": "គណនាការប្រាកប្រចាំថ្ងៃប័នស្មានអត្រាការប្រាកដែលមិនស្គាល់",
    "calc.simple_monthly.name": "ការប្រាកសាមញ្ញ – ប្រចាំខែ/ឆ្នាំ",
    "calc.simple_monthly.desc": "ការប្រាកសាមញ្ញប្រចាំខែ៤ឆ្នាំប័នស្មានអត្រាដែលមិនស្គាល់",
    "calc.loan4.name": "ម៉ាស៊ីនគណនាឥណទាន (៤ ផ្នែក)",
    "calc.loan4.desc": "ដោះស្រាយសម្រាប់ការបាត់បង់ផ្នែកណាមួយនៃឥណទាន (ប្រាក់ដើម ការប្រាក់ រយៈពេល ការទូទាត់)",
    "calc.compound_loan.name": "ប្រាក់កម្ចីការប្រាក់ផ្សំ",
    "calc.compound_loan.desc": "កាលវិភាគសងប្រាក់កម្ចីពេញលេញ មានការគណនាថ្ងៃបុណ្យ និងការកែតម្រូវ",
    "calc.loan_flexible.name": "ប្រាក់កម្ចីបែបបត់បែន (ដើមតុនជាកម្រើក)",
    "calc.loan_flexible.desc": "ការប្រាក់គិតប្រចាំខែ ដើមតុនសងជាដុំតាមកំណត់",
    "calc.loan_multi_rate.name": "ប្រាក់កម្ចី — អត្រាច្រើន",
    "calc.loan_multi_rate.desc": "ប្រាក់កម្ចីដែលមានការប្រែប្រួលអត្រា មានការគណនាការប្រាក់ពិន័យ",
    "calc.loan_adjusted.name": "ការប្រៀបធៀបការរចំសម្រួលប្រាក់កម្ចី",
    "calc.loan_adjusted.desc": "ប្រៀបធៀបលក្ខខណ្ឌប្រាក់កម្ចីបច្ចុប្បន្ន និងដែលបានស្នើរ — គណនាការបង់តិច និងការប្រែប្រួលអត្រា",
    "calc.loan_comp.name": "ការប្រើបធ្រឹប្រាកកម្ចឹ",
    "calc.loan_comp.desc": "ការតូតកាត់ស្មើ ៤ ដើមតុនស្មើដែលឈ្វែងឈ្វាង",
    "calc.promo.name": "ប្រាកកម្ចឹប្រម័ស៊ឹន",
    "calc.promo.desc": "ប្រាកកម្ចឹដែលមានអត្រាការប្រាកខុស។។គ្នា",
    "calc.cambodia_loans.name": "ប្រើបធ្រឹប្រាកកម្ចឹកម្ពុជា",
    "calc.cambodia_loans.desc": "ប្រើបធ្រឹប្រភេតបញ្កាទូទែដែលមាននៅកម្ពុជា",
    "calc.credit_card.name": "បញ្កាត៊ឲណតាន",
    "calc.credit_card.desc": "យលដឹងអានត្លេដើមបិតេប្រាកនៃការត៊ឲណតាន",
    "calc.debt_payoff.name": "យុត្ធសាស្ត្រសងបញ្កា",
    "calc.debt_payoff.desc": "ស្វែងរកផ្លូវល័ឡបម្ពាស់ដើម្បីសងបញ្កាច្រើន",
    "calc.dti.name": "សមាមាត្របញ្កាតីចានដោល",
    "calc.dti.desc": "កឳនត់សមត្ថភាពក្នងការត្វឹរចានបញ្កាផ្តែហ និងបញ្កាផសេង",
    "calc.rent_vs_buy.name": "ជួល ឬ ទិញ",
    "calc.rent_vs_buy.desc": "តើការជួល ឬការទិញផ្ទះតម្លៃថោកជាង?",
    "calc.family_budget.name": "ថវិកាគ្រួសារ",
    "calc.family_budget.desc": "ការរើបចតថវិកាមូលដ្ឋានសម្រាបគ្រួសារ",
    "calc.church_budget.name": "ថវិកាព្រែវិហារ",
    "calc.church_budget.desc": "ឧបករណ៍សាមញ្ញសម្រាប់ធ្វើថវិកាព្រះវិហារ",
    "calc.farm_budget.name": "ថវិកាដាំណាំ",
    "calc.farm_budget.desc": "គណនាថាតើលដាំណាំមួយមានប្រាកចានេមឹអត់",
    "calc.insurance.name": "ធានារ័ប្រង – បញ្កាប់មុន?",
    "calc.insurance.desc": "វាយតម្លថាតើលការបញ្កាប់ប័ណ្ណឹក្សាធានារ័ប្រងជាគាលល័ឡ",
    "calc.inflation.name": "ម័ស៊ឹនគណនាអតិផរណាកម្ពុជា",
    "calc.inflation.desc": "ចានសមប្រាកថែរមានតម្ល័ប័ម្នក្នុងស្ណានភ្កបច្ចុប្បន្ន?",
    "input.label": "ការបញ្ចូល",
    "input.main": "ការបញ្ចូលចម្បង",
    "input.optional": "ការកឳនត់បន្ថែម",
    "input.annual_rate": "អត្រាការប្រាកប្រចាំឆ្នាំ",
    "input.time_period": "រយែពេល",
    "input.unit": "អ៊ហវ្ហ​ឨកតា",
    "input.years": "ឆ្នាំ",
    "input.months": "ខែ",
    "input.comp_freq": "ការប្រាកការប្រាក",
    "input.freq.monthly": "ប្រចាំខែ",
    "input.freq.quarterly": "ប្រចាំត្រឹមាស",
    "input.freq.semi": "ប្រចាំពាក់ឆ្នាំ",
    "input.freq.annual": "ប្រចាំឆ្នាំ",
    "input.freq.daily": "ប្រចាំថ្ងៃ",
    "input.nationality": "ប្រភេតម្ចាស់ប្រាក",
    "input.nat.national": "ជនជាតិខ្មែរ (ពន្ធ ៦%)",
    "input.nat.foreigner": "បរទេស (ពន្ធ ១២%)",
    "input.days_unit": "ថ្ងៃ",
    "btn.calculate": "គណនា",
    "result.summary": "សង្ខេបលត្ធផល",
    "result.effective_rate": "តិន្នផលប្រចាំឆ្នាំជាក់ស័ត្តែ",
    "result.rule72": "ឆ្នាំដើម្បីត្វែដង (ច្បាប់ ៧ ។ ។ )",
    "result.quick_cmp": "ការប្រើបធ្រឹរហ័ស់",
    "cmp.scenario": "ករណ៍",
    "cmp.future_value": "តម្ល័អនាគត",
    "cmp.current": "▶ ផែនការបច្ចុប្បន្ន",
    "cmp.plus1": "ប្រសិនអត្រា +១%",
    "cmp.minus1": "ប្រសិនអត្រា −១%",
    "cmp.double_time": "ត្វែដងរយែពេល",
    "fixed.page_title": "ម័ស៊ឹនគណនាការសន្សាំប្រភេតថែរ",
    "fixed.page_desc": "មើលពីរប្បិហនោទឹប្រាកបញ្ញើត្បើនរឹកចម្រើនជាមួយការប្រាកផ្នត់តាមពេវេលា។",
    "fixed.bread": "ម័ស៊ឹនគណនាការសន្សាំប្រភេតថែរ",
    "fixed.print_title": "ម័ស៊ឹនគណនាការសន្សាំប្រភេតថែរ",
    "fixed.input.principal": "ប្រាកបញ្ញើដាំបឹ",
    "fixed.result.future_value_net": "តម្ល័អនាគតក្រោយពន្ធ",
    "fixed.result.principal": "ប្រាកបញ្ញើដាំបឹ",
    "fixed.result.gross_interest": "ការប្រាកមុនកាត់ពន្ធ",
    "fixed.result.tax_deducted": "ពន្ធបានកាត់",
    "fixed.result.net_interest": "ការប្រាកក្រោយកាត់ពន្ធ",
    "fixed.chart.title": "គាំនូសតាងការលូតលាស់ការសន្សាំ",
    "fixed.chart.net_balance": "សមតុល្យក្រោយពន្ធ",
    "fixed.chart.gross_balance": "សមតុល្យមុនពន្ធ",
    "fixed.chart.principal": "ដើមតុន",
    "cmp.fixed.half": "ប្រសិនប្រាកបញ្ញើ ÷ ២",
    "cmp.fixed.double": "ប្រសិនប្រាកបញ្ញើ × ២",
    "simple_monthly.page_title": "ម័ស៊ឹនគណនាការសងប្រចាំខែ/ឆ្នាំ",
    "simple_monthly.page_desc": "គណនាការប្រាក់និងកាលវិភាគសង សម្រាប់ប្រាក់កម្ចីការប្រាក់សាមញ្ញ។ ជ្រើសរើសថាតើការប្រាក់គិតប្រចាំខែ ឬប្រចាំឆ្នាំ ហើយថាតើគិតលើដើមតុនដើម ឬដើមតុននៅសល់។",
    "simple_monthly.bread": "ការប្រាក់សាមញ្ញ – ប្រចាំខែ/ឆ្នាំ",
    "simple_monthly.print_title": "ម័ស៊ឹនគណនាការសងប្រចាំខែ/ឆ្នាំ",
    "simple_monthly.card.payment": "ការកំណត់ការទូទាត់",
    "simple_monthly.input.rate": "អត្រាការប្រាក់",
    "simple_monthly.input.rate_period": "រយៈពេលអត្រា",
    "simple_monthly.input.period.monthly": "ក្នុងមួយខែ",
    "simple_monthly.input.period.yearly": "ក្នុងមួយឆ្នាំ",
    "simple_monthly.input.interest_base": "គណនាការប្រាក់លើ",
    "simple_monthly.input.base.original": "ដើមតុនដើម",
    "simple_monthly.input.base.remaining": "ដើមតុននៅសល់",
    "simple_monthly.input.principal_label": "ការបង់ដើមតុន (ជម្រើស)",
    "simple_monthly.input.principal_hint": "កំណត់ការទូទាត់ប្រចាំខែដែលច្រើនជាងការប្រាក់ ដើម្បីចាប់ផ្ដើមសងដើមតុន។",
    "simple_monthly.input.new_payment": "ការទូទាត់ប្រចាំខែ",
    "simple_monthly.input.new_payment_date": "ថ្ងៃចាប់ផ្ដើម (ជម្រើស)",
    "simple_monthly.result.total_repaid": "ចំនួនទឹកប្រាក់សរុបបានសង",
    "simple_monthly.result.interest_only": "ការប្រាក់ប្រចាំខែ",
    "simple_monthly.result.never_paid": "គ្មានថ្ងៃបញ្ចប់",
    "simple_monthly.result.never_paid_hint": "ប្រាក់កម្ចីមិនត្រូវបានសង — កំណត់ការទូទាត់ច្រើនជាងការប្រាក់ ដើម្បីសងដើមតុន",
    "simple_monthly.result.total_interest": "ការប្រាក់សរុបបានបង់",
    "simple_monthly.result.monthly_interest": "ការប្រាក់ប្រចាំខែ",
    "simple_monthly.result.yearly_interest": "ការប្រាក់ប្រចាំឆ្នាំ",
    "simple_monthly.result.term": "រយៈពេលកម្ចី",
    "simple_monthly.result.months": "ខែ",
    "simple_monthly.result.partial": "មួយផ្នែក",
    "simple_monthly.per_month": "/ខែ",
    "simple_monthly.per_year": "/ឆ្នាំ",
    "simple_monthly.chart.title": "ដើមតុននៅសល់តាមពេលវេលា",
    "simple_monthly.chart.balance": "ដើមតុននៅសល់",
    "simple_monthly.sched.month": "ខែ",
    "simple_monthly.sched.interest": "ការប្រាក់",
    "simple_monthly.sched.payment": "ការទូទាត់",
    "simple_monthly.sched.principal_paid": "ដើមតុនបានសង",
    "simple_monthly.sched.never_paid_note": "លំនាំនេះបន្តគ្មានទីបញ្ចប់។ កំណត់ការទូទាត់ប្រចាំខែច្រើនជាងការប្រាក់ ដើម្បីសងប្រាក់កម្ចី។",
    "simple_daily.page_title": "ម័ស៊ឹនគណនាការសងប្រចាំថ្ងៃ",
    "simple_daily.page_desc": "បញ្ចូលចានប្រាកកម្ចឹ និងចានសរុបដែលត្រូវសង ដើម្បីមើលការតូតកាត់ប្រចាំថ្ងៃ និងអត្រាការប្រាកប្រចាំឆ្នាំពិតប្រាកដ សម្រាប់ជម្រើសសងរហូតដល់បី។",
    "simple_daily.bread": "ការប្រាកសាមញ្ញ – ប្រចាំថ្ងៃ",
    "simple_daily.print_title": "ម័ស៊ឹនគណនាការសងប្រចាំថ្ងៃ",
    "simple_daily.input.currency": "រូបិយបត្ត",
    "simple_daily.input.loan": "ចានប្រាកកម្ចឹ (ដើមតុន)",
    "simple_daily.input.payback": "ចានសរុបដែលត្រូវសង",
    "simple_daily.input.start_date": "កាលបរិច្ឆេតផ្ដើមប្រាកកម្ចឹ (ជម្រើស)",
    "simple_daily.input.options_label": "ជម្រើសសងប្រចាំថ្ងៃ",
    "simple_daily.input.opt1": "ជម្រើស ១",
    "simple_daily.input.opt2": "ជម្រើស ២",
    "simple_daily.input.opt3": "ជម្រើស ៣",
    "simple_daily.result.total_interest": "ការប្រាកសរុប (ចំណេញម្ចាស់ប្រាក)",
    "simple_daily.result.loan_amount": "ចានប្រាកកម្ចឹ",
    "simple_daily.result.payback_amount": "ចានសរុបដែលត្រូវសង",
    "simple_daily.result.comparison": "ការប្រើបធ្រឹជម្រើស",
    "simple_daily.result.option_col": "ជម្រើស",
    "simple_daily.result.days_col": "ថ្ងៃ",
    "simple_daily.result.daily_pmt_col": "ការតូតកាត់ប្រចាំថ្ងៃ",
    "simple_daily.result.annual_rate_col": "អត្រាប្រចាំឆ្នាំ",
    "simple_daily.chart.title": "សមតុល្យប្រចាំថ្ងៃដែលនៅសល់",
    "simple_daily.chart.opt1": "ជម្រើស ១",
    "simple_daily.chart.opt2": "ជម្រើស ២",
    "simple_daily.chart.opt3": "ជម្រើស ៣",
    "simple_daily.sched.day": "ថ្ងៃ",
    "simple_daily.sched.date": "កាលបរិច្ឆេត",
    "monthly.page_title": "ម័ស៊ឹនគណនាការសន្សាំប្រចាំខែ",
    "monthly.page_desc": "មើលពីរប្បិហនោទឹការបញ្ញើប្រចាំខែ — ជាមួយ ៤ គ្មានប្រាកបញ្ញើដាំបឹ — រឹកចម្រើនតាមពេវេលា។",
    "monthly.bread": "ម័ស៊ឹនគណនាការសន្សាំប្រចាំខែ",
    "monthly.print_title": "ម័ស៊ឹនគណនាការសន្សាំប្រចាំខែ",
    "monthly.input.contrib": "ការបញ្ចូលប្រចាំខែ",
    "monthly.input.principal": "ប្រាកបញ្ញើដាំបឹ (ជម្រើស)",
    "monthly.input.timing": "ពេវេលបញ្ចូល",
    "monthly.timing.end": "ចុងរយែពេល",
    "monthly.timing.begin": "ដើមរយែពេល",
    "monthly.result.future_value": "តម្ល័អនាគត",
    "monthly.result.future_value_net": "តម្ល័អនាគតក្រោយពន្ធ",
    "monthly.result.principal": "ប្រាកបញ្ញើដាំបឹ",
    "monthly.result.total_contribs": "ការបញ្ចូលសរុប",
    "monthly.result.total_principal": "ដើមតុនសរុបដែលបានវិនិយឹគ",
    "monthly.result.total_interest": "ការប្រាកសរុបត្វឹរបាន",
    "monthly.result.gross_interest": "ការប្រាកមុនកាត់ពន្ធ",
    "monthly.result.tax_deducted": "ពន្ធបានកាត់",
    "monthly.result.net_interest": "ការប្រាកក្រោយកាត់ពន្ធ",
    "monthly.chart.title": "គាំនូសតាងការលូតលាស់ការសន្សាំ",
    "monthly.chart.balance": "សមតុល្យក្រោយពន្ធ",
    "monthly.chart.gross_balance": "សមតុល្យមុនពន្ធ",
    "monthly.chart.invested": "ការវិនិយឹគសរុប",
    "cmp.monthly.lump_only": "ប្រាកបញ្ញើត្បើន (គ្មានប្រចាំខែ)",
    "cmp.monthly.month_only": "ប្រចាំខែត្បើន (គ្មានប្រាកបញ្ញើដាំបឹ)",
    "loan.page_title": "ម័ស៊ឹនគណនាប្រាកកម្ចឹ (៤ ផ្នែក)",
    "loan.page_desc": "ដឹងអានអត្វរប្រាកកម្ចឹ ៣? ស្វែងរកអត្វរតី ៤ — ការតូតកាត់, ដើមតុន, អត្រាការប្រាក, ៤រយែពេល។",
    "loan.bread": "ម័ស៊ឹនគណនាប្រាកកម្ចឹ (៤ ផ្នែក)",
    "loan.print_title": "ម័ស៊ឹនគណនាប្រាកកម្ចឹ (៤ ផ្នែក)",
    "loan.section.currency": "រូបិយបត្ត",
    "loan.exrate": "អត្រាប្តូរូបិយបត្ត (1 ដុល្លារ =)",
    "loan.section.solve": "ស្វែងរក",
    "loan.solve.payment": "ការតូតកាត់\nប្រចាំខែ",
    "loan.solve.principal": "ចាន\nប្រាកកម្ចឹ",
    "loan.solve.rate": "អត្រា\nការប្រាក",
    "loan.solve.nper": "រយែពេល\nកម្ចឹ",
    "loan.section.details": "ព័ត៌មានប្រាកកម្ចឹ",
    "loan.input.principal": "ចានប្រាកកម្ចឹ",
    "loan.input.rate": "អត្រាការប្រាកប្រចាំឆ្នាំ",
    "loan.input.term": "រយែពេលកម្ចឹ",
    "loan.input.payment": "ការតូតកាត់ប្រចាំខែ",
    "loan.result.principal": "ចានប្រាកកម្ចឹ",
    "loan.result.payment": "ការតូតកាត់ប្រចាំខែ",
    "loan.result.total_paid": "ចានសរុបបានបង់",
    "loan.result.total_interest": "ការប្រាកសរុបបានបង់",
    "loan.result.interest_pct": "ការប្រាកជា % នៃដើមតុន",
    "loan.result.term": "រយែពេលកម្ចឹ",
    "loan.hero.payment": "ការតូតកាត់ប្រចាំខែ",
    "loan.hero.principal": "ចានប្រាកកម្ចឹ",
    "loan.hero.rate": "អត្រាការប្រាកប្រចាំឆ្នាំ",
    "loan.hero.nper": "រយែពេលកម្ចឹ",
    "loan.chart.title": "សមតុល្យប្រាកកម្ចឹតាមពេវេលា",
    "loan.chart.balance": "សមតុល្យដែលនៅសល់",
    "loan.chart.cum_interest": "ការប្រាកសរុបបានបង់",
    "loan.schedule.title": "តារាងការសងប្រាកកម្ចឹ",
    "loan.sched.payment_num": "ការតូតកាត់ #",
    "loan.sched.payment": "ការតូតកាត់",
    "loan.sched.principal": "ដើមតុន",
    "loan.sched.remaining": "សមតុល្យដែលនៅសល់",
    "cmp.loan.header.pmt": "តូតកាត់/ខែ",
    "cmp.loan.header.int": "ការប្រាកសរុប",
    "cmp.loan.plus1": "អត្រា +១%",
    "cmp.loan.minus1": "អត្រា −១%",
    "cmp.loan.1yr": "រយែពេល ១ ឆ្នាំ",
    "cmp.loan.3yr": "រយែពេល ៣ ឆ្នាំ",
    "schedule.title": "កាលវិភាគតាមរយែពេល",
    "schedule.show": "បង្ហាញកាលវិភាគ",
    "schedule.hide": "លាកកាលវិភាគ",
    "sched.period": "រយែពេល",
    "sched.date": "កាលបរិច្ឆេត",
    "sched.beg_balance": "សមតុល្យដាំបឹ",
    "sched.interest": "ការប្រាកត្វឹរបាន",
    "sched.gross_interest": "ការប្រាកមុនពន្ធ",
    "sched.tax": "ពន្ធ",
    "sched.net_interest": "ការប្រាកក្រោយពន្ធ",
    "sched.end_balance": "សមតុល្យចុងក្រោយ",
    "sched.cum_interest": "ការប្រាកសរុប",
    "sched.cum_net_interest": "ការប្រាកសរុបក្រោយពន្ធ",
    "sched.cum_contribs": "ការបញ្ចូលសរុប",
    "fl.page_title": "ប្រាក់កម្ចីបែបបត់បែន — ដើមតុនជាកម្រើក",
    "fl.page_desc": "ការប្រាក់ត្រូវបានគណនាប្រចាំខែ។ ដើមតុនត្រូវបានសងជាដុំតាមអំឡុងពេលកំណត់ ។ បង្កើតកាលវិភាគពេញលេញ ជាមួយការគេចថ្ងៃបុណ្យ។",
    "fl.bread": "ប្រាក់កម្ចីបែបបត់បែន",
    "fl.print_title": "ម័ស៊ឹនគណនាប្រាក់កម្ចីបែបបត់បែន",
    "fl.section.loan": "ព័ត៌មានប្រាក់កម្ចី",
    "fl.section.dates": "កាលបរិច្ឆេត",
    "fl.section.settings": "ការកំណត់",
    "fl.section.structure": "រចនាសម្ព័ន្ធការទូទាត់",
    "fl.input.loan_amount": "ចំនួនប្រាក់កម្ចី",
    "fl.input.rate": "អត្រាការប្រាក់ប្រចាំឆ្នាំ",
    "fl.input.term": "រយៈពេលកម្ចី",
    "fl.input.start_date": "ថ្ងៃចាប់ផ្ដើមប្រាក់កម្ចី",
    "fl.input.override_date": "ថ្ងៃចាប់ផ្ដើមជំនួស",
    "fl.input.override_hint": "ជម្រើស – ជំនួសកាលបរិច្ឆេតយោងសម្រាប់ការគណនាថ្ងៃដំបូង",
    "fl.input.first_payment": "ថ្ងៃទូទាត់ដំបូង",
    "fl.input.day_count": "វិធីគណនាថ្ងៃ",
    "fl.day_count.standard": "ស្ដង់ដារ – ថ្ងៃពិតប្រាកដ / 360",
    "fl.day_count.actual": "ពិតប្រាកដ – ថ្ងៃពិតប្រាកដ / 365",
    "fl.input.delay_rule": "ច្បាប់ថ្ងៃទូទាត់",
    "fl.delay.none": "គ្មានការកែតម្រូវ",
    "fl.delay.skip_sun": "គេចថ្ងៃអាទិត្យ",
    "fl.delay.skip_sat_sun": "គេចថ្ងៃសៅរ៍ និងអាទិត្យ",
    "fl.delay.skip_sun_hol": "គេចថ្ងៃអាទិត្យ និងបុណ្យជាតិ",
    "fl.delay.skip_all": "គេចថ្ងៃសៅរ៍ អាទិត្យ និងបុណ្យជាតិ",
    "fl.input.frequency": "ចំនួនខែរវាងការសងដើមតុន",
    "fl.input.frequency_unit": "ខែ",
    "fl.input.freq_start": "ថ្ងៃចាប់ផ្ដើមវដ្ត",
    "fl.input.fixed_principal": "ដើមតុនថែរ / ការទូទាត់",
    "fl.principal.auto": "ស្វ័យប្រវត្តិ",
    "fl.principal.reset": "កំណត់ស្វ័យប្រវត្តិ",
    "fl.input.defer": "ពន្យារការប្រាក់ទៅថ្ងៃទូទាត់",
    "fl.defer.no": "ទេ – បង់ការប្រាក់ប្រចាំខែ",
    "fl.defer.yes": "បាទ/ចាស – ប្រមូល ហើយបង់ជាមួយដើមតុន",
    "fl.result.monthly_interest": "ការប្រាក់ប្រចាំខែ (ធម្មតា)",
    "fl.result.lump_sum": "ដើមតុនជាដុំ",
    "fl.result.total_paid": "ចំនួនទឹកប្រាក់សរុបបានបង់",
    "fl.result.total_principal": "ដើមតុនសរុប",
    "fl.result.total_interest": "ការប្រាក់សរុប",
    "fl.result.maturity": "ថ្ងៃផុតកំណត់",
    "fl.chart.title": "សមតុល្យប្រាក់កម្ចីតាមពេលវេលា",
    "fl.chart.balance": "សមតុល្យដែលនៅសល់",
    "fl.chart.cum_interest": "ការប្រាក់សរុបបំរើ",
    "fl.sched.title": "កាលវិភាគសងប្រាក់",
    "fl.sched.num": "លំ.",
    "fl.sched.date": "ថ្ងៃទូទាត់",
    "fl.sched.days": "ថ្ងៃ",
    "fl.sched.principal": "ដើមតុន",
    "fl.sched.interest": "ការប្រាក់",
    "fl.sched.total": "សរុប",
    "fl.sched.balance": "សមតុល្យ",
    "fl.sched.totals": "សរុបទាំងអស់",
    "ef.page_title": "ម័ស៊ឹនគណនាមូលនិធិបន្តាន់",
    "ef.page_desc": "បញ្ចូលការចំណាយប្រចាំខែ ដើម្បីដឹងថាតើអ្នកត្រូវការប្រាក់ប៉ុន្មានសម្រាប់មូលនិធិបន្តាន់។ អ្នកជំនាញណែនាំឱ្យសន្សាំ ៣-៦ ខែ នៃការចំណាយ។",
    "ef.bread": "មូលនិធិបន្តាន់",
    "ef.print_title": "ម័ស៊ឹនគណនាមូលនិធិបន្តាន់",
    "ef.section.expenses": "ការចំណាយប្រចាំខែ",
    "ef.col.amount": "ចំនួន",
    "ef.input.housing": "លំនៅដ្ឋាន (ថ្លៃជួល, ភ្លើង, ទឹក)",
    "ef.input.food": "អាហារ",
    "ef.input.transport": "យានដ្ឋាន",
    "ef.input.debt": "ការសងបំណុល",
    "ef.input.education": "ការអប់រំកូន",
    "ef.input.phone": "ទូរស័ព្ទ",
    "ef.input.insurance": "ធានារ័ប្រង",
    "ef.input.property_tax": "ពន្ធដីធ្លី",
    "ef.input.other": "ផ្សេងៗ",
    "ef.total": "ការចំណាយប្រចាំខែសរុប",
    "ef.goals.title": "គោលដៅមូលនិធិបន្តាន់",
    "ef.level.basic_dot": "មូលដ្ឋាន",
    "ef.level.good_dot": "ល្អ",
    "ef.level.better_dot": "ល្អជាង",
    "ef.level.basic_desc": "ការចំណាយ ១ ខែ",
    "ef.level.good_desc": "ការចំណាយ ៣ ខែ",
    "ef.level.better_desc": "ការចំណាយ ៦ ខែ",
    "ef.goal.basic": "១ ខែ - មូលដ្ឋាន",
    "ef.goal.basic_sub": "អប្បបរមាដែលណែនាំ",
    "ef.goal.good": "៣ ខែ - ល្អ",
    "ef.goal.good_sub": "ការណែនាំស្ដង់ដារ",
    "ef.goal.better": "៦ ខែ - ល្អជាង",
    "ef.goal.better_sub": "ការអនុវត្តល្អបំផុត",
    "ef.chart.title": "គោលដៅមូលនិធិបន្តាន់",
    "cln.page_title": "ប្រាក់កម្ចីការប្រាក់ផ្សំ",
    "cln.page_desc": "បង្កើតកាលវិភាគសងប្រាក់ពេញលេញដោយផ្អែកលើកាលបរិច្ឆេត។ ជ្រើស 30/360 ឬ Actual/360 ហើយដំណើរការដោយស្វ័យប្រវត្តិ ដើម្បីគេចថ្ងៃអាទិត្យ ឬថ្ងៃបុណ្យជាតិ។",
    "cln.bread": "ប្រាក់កម្ចីការប្រាក់ផ្សំ",
    "cln.print_title": "ម័ស៊ឹនគណនាប្រាក់កម្ចីការប្រាក់ផ្សំ",
    "cln.input.loan_amount": "ចំនួនប្រាក់កម្ចី",
    "cln.input.rate": "អត្រាការប្រាក់ប្រចាំឆ្នាំ",
    "cln.input.term": "រយៈពេលកម្ចី",
    "cln.input.start_date": "ថ្ងៃចាប់ផ្ដើមប្រាក់កម្ចី",
    "cln.input.first_payment": "ថ្ងៃទូទាត់ដំបូង",
    "cln.input.day_count": "វិធីគណនាថ្ងៃ",
    "cln.day_count.30_360": "30/360 (អត្រា ÷ 12)",
    "cln.day_count.actual_360": "Actual/360 (អត្រា ÷ 360 × ថ្ងៃ)",
    "cln.input.delay_rule": "ច្បាប់ថ្ងៃទូទាត់",
    "cln.delay.none": "គ្មានការកែតម្រូវ",
    "cln.delay.skip_sun": "គេចថ្ងៃអាទិត្យ → ថ្ងៃច័ន្ទ",
    "cln.delay.skip_sun_hol": "គេចថ្ងៃអាទិត្យ និងបុណ្យជាតិ",
    "cln.delay.skip_sat_sun": "គេចថ្ងៃសៅរ៍ និងអាទិត្យ → ថ្ងៃច័ន្ទ",
    "cln.delay.skip_sat_sun_hol": "គេចថ្ងៃសៅរ៍ អាទិត្យ និងបុណ្យជាតិ",
    "cln.input.payment": "ការទូទាត់ប្រចាំខែ",
    "cln.input.payment_auto": "ស្វ័យប្រវត្តិ",
    "cln.override_reset": "កំណត់ស្វ័យប្រវត្តិ",
    "cln.result.payment": "ការទូទាត់ប្រចាំខែ",
    "cln.result.num_payments": "ចំនួនការទូទាត់",
    "cln.result.total_paid": "ចំនួនទឹកប្រាក់សរុបបានបង់",
    "cln.result.total_interest": "ការប្រាក់សរុបបានបង់",
    "cln.result.total_principal": "ដើមតុនសរុបបានសង",
    "cln.result.final_date": "ថ្ងៃទូទាត់ចុងក្រោយ",
    "cln.hint.start_date": "ជម្រើស — ប្រើថ្ងៃនេះប្រសិនបើទទេ",
    "cln.hint.first_payment": "ជម្រើស — ស្វ័យប្រវត្តិ ១ ខែក្រោយថ្ងៃចាប់ផ្ដើម",
    "lcp.page_title": "ម័ស៊ឹនគណនាប្រៀបធៀបប្រាក់កម្ចី",
    "lcp.page_desc": "ប្រៀបធៀបការបង់ស្មើ (សងប្រចាំខែ) ជាមួយការសងដើមតុនស្មើគ្នា។ មើលថាតើវិធីណាចំណាយការប្រាក់តិចជាង។",
    "lcp.bread": "ប្រៀបធៀបប្រាក់កម្ចី",
    "lcp.print_title": "ម័ស៊ឹនគណនាប្រៀបធៀបប្រាក់កម្ចី",
    "lcp.col.ep": "ការទូទាត់ស្មើ",
    "lcp.col.ep_desc": "ចំនួនស្មើគ្នារៀងខែ",
    "lcp.col.epr": "ដើមតុនស្មើ",
    "lcp.col.epr_desc": "ដើមតុនថែររៀងខែ ការទូទាត់ថយចុះ",
    "lcp.result.monthly_payment": "ការទូទាត់ប្រចាំខែ",
    "lcp.result.first_payment": "ការទូទាត់ដំបូង",
    "lcp.result.last_payment": "ការទូទាត់ចុងក្រោយ",
    "lcp.result.total_paid": "ចំនួនសរុបបានបង់",
    "lcp.result.total_interest": "ការប្រាក់សរុបបានបង់",
    "lcp.result.num_payments": "ចំនួនការទូទាត់",
    "lcp.result.final_date": "ថ្ងៃទូទាត់ចុងក្រោយ",
    "lcp.savings.saves": "សន្សំ",
    "lcp.savings.note_epr": "ការប្រាក់សរុប ធៀបនឹង ការទូទាត់ស្មើ",
    "lcp.savings.note_ep": "ការប្រាក់សរុប ធៀបនឹង ដើមតុនស្មើ",
    "lcp.chart.title": "សមតុល្យប្រាក់កម្ចីតាមពេលវេលា",
    "lcp.chart.ep_balance": "ការទូទាត់ស្មើ — សមតុល្យ",
    "lcp.chart.epr_balance": "ដើមតុនស្មើ — សមតុល្យ",
    "lcp.chart.ep_principal": "ការទូទាត់ស្មើ — ដើមតុន",
    "lcp.chart.ep_interest": "ការទូទាត់ស្មើ — ការប្រាក់",
    "lcp.chart.epr_principal": "ដើមតុនស្មើ — ដើមតុន",
    "lcp.chart.epr_interest": "ដើមតុនស្មើ — ការប្រាក់",
    "lcp.chart.view_balance": "សមតុល្យ",
    "lcp.chart.view_split": "ការបំបែកការទូទាត់",
    "currency.khr_note": "អត្រាប្តូរ: ៤,០០០ រៀល = ១ ដុល្លារ (ថែរ)",
    "cln.chart.title": "សមតុល្យប្រាក់កម្ចីតាមពេលវេលា",
    "cln.chart.balance": "សមតុល្យដែលនៅសល់",
    "cln.chart.cum_interest": "ការប្រាក់សរុបបំរើ",
    "cln.sched.title": "កាលវិភាគសងប្រាក់",
    "cln.sched.num": "ការទូទាត់ #",
    "cln.sched.date": "កាលបរិច្ឆេត",
    "cln.sched.days": "ថ្ងៃ",
    "cln.sched.principal": "ដើមតុន",
    "cln.sched.interest": "ការប្រាក់",
    "cln.sched.payment": "ការទូទាត់",
    "cln.sched.balance": "សមតុល្យ",
    "cln.sched.totals": "សរុប",
    "print.note": "ចុច <strong>បឹកពិម្ព / រក្សាតុកជា PDF</strong> ដើម្បីនាំចេញលត្ធផល។",
    "print.btn": "បឹកពិម្ព / រក្សាតុកជា PDF",
    "print.date_prefix": "បឹកពិម្ពនៅ",
    "cmr.page_title": "ប្រាក់កម្ចីដើម-ប្រាក់ — អត្រាជាច្រើន",
    "cmr.page_desc": "បង្កើតកាលវិភាគសងប្រាក់ពេញលេញសម្រាប់ប្រាក់កម្ចីដែលមានអត្រាការប្រាក់ប្រែប្រួល។ តាមដានការទូទាត់ជាក់ស្ដែង និងគណនាពិន័យការទូទាត់យឺត។",
    "cmr.bread": "ប្រាក់កម្ចី — អត្រាជាច្រើន",
    "cmr.print_title": "ម័ស៊ឹនគណនាប្រាក់កម្ចី — អត្រាជាច្រើន",
    "cmr.section.periods": "វ័ណអត្រា",
    "cmr.period_label": "វ័ណ {n}",
    "cmr.input.penalty_rate": "អត្រាពិន័យ (ប្រចាំឆ្នាំ)",
    "cmr.hint.penalty_rate": "អនុវត្តលើចំនួនមិនបានបង់នៅក្នុងម័ស៊ឹនគណនាពិន័យខាងក្រោម",
    "cmr.input.period_start": "ថ្ងៃចាប់ផ្ដើមវ័ណ",
    "cmr.hint.period_start": "ថ្ងៃទូទាត់ដំបូងនៃអត្រានេះ",
    "cmr.btn.add_period": "+ បន្ថែមវ័ណអត្រា",
    "cmr.btn.remove_period": "លុប",
    "cmr.error.period_date_required": "ថ្ងៃចាប់ផ្ដើមវ័ណ {n} ត្រូវការ។",
    "cmr.error.period_date_order": "ថ្ងៃចាប់ផ្ដើមវ័ណត្រូវតែក្រោយថ្ងៃចាប់ផ្ដើមប្រាក់កម្ចី។",
    "cmr.error.first_date_order": "ថ្ងៃទូទាត់ដំបូងត្រូវតែក្រោយថ្ងៃចាប់ផ្ដើមប្រាក់កម្ចី។",
    "cmr.sched.status": "ស្ថានភាព",
    "cmr.sched.paid": "បានបង់",
    "cmr.sched.notes": "កំណត់ចំណាំ",
    "cmr.status.paid_full": "បង់ពេញ",
    "cmr.status.partial": "បង់មួយផ្នែក",
    "cmr.late.section": "ម័ស៊ឹនគណនាពិន័យការទូទាត់យឺត",
    "cmr.late.desc": "បញ្ចូលកាលបរិច្ឆេទដើម្បីមើលពិន័យលើការទូទាត់ដែលមិនទាន់បង់ ឬបង់មួយផ្នែក។",
    "cmr.late.as_of": "គណនារហូតដល់",
    "cmr.late.no_calc": "បញ្ចូលកាលបរិច្ឆេទ \"រហូតដល់\" ខាងលើដើម្បីគណនាពិន័យ។",
    "cmr.late.none": "រកឃើញការទូទាត់ហួសកំណត់គ្មានទេ។",
    "cmr.late.num": "#",
    "cmr.late.date_col": "ថ្ងៃដល់កំណត់",
    "cmr.late.days_col": "ថ្ងៃហួស",
    "cmr.late.installment": "ការដំឡើង",
    "cmr.late.paid_col": "បានបង់",
    "cmr.late.unpaid_col": "មិនទាន់បង់",
    "cmr.late.penalty_col": "ពិន័យ",
    "cmr.late.total_col": "សរុបហួសកំណត់",
    "cmr.late.total_row": "សរុប",
    "cmr.late.remaining_loan": "សមតុល្យប្រាក់កម្ចីដែលនៅសល់",
    "cmr.late.total_penalty": "ពិន័យសរុបបន្ថែម",
    "cmr.late.grand_total": "សរុបទឹកប្រាក់ដែលជំពាក់",
    "cinf.page_title": "ម័ស៊ឹនគណនាអតិផរណាកម្ពុជា",
    "cinf.desc": "មើលពីរបៀបដែលថាមពលទិញទំនិញប្ដូរប្រែតាមពេលវេលានៅកម្ពុជា ដោយប្រើទិន្នន័យ CPI ផ្លូវការពីវិទ្យាស្ថានជាតិស្ថិតិ។",
    "cinf.section.inputs": "ទិន្នន័យបញ្ចូល",
    "cinf.section.results": "លទ្ធផល",
    "cinf.input.amount": "ចំនួនទឹកប្រាក់",
    "cinf.input.from_date": "ពីខែ",
    "cinf.input.to_date": "ដល់ខែ",
    "cinf.note.source_label": "ប្រភពទិន្នន័យ:",
    "cinf.note.source": "វិទ្យាស្ថានជាតិស្ថិតិ (NIS), កម្ពុជា។ មូលដ្ឋាន CPI: តុលា–ធ្នូ ២០០៦ = ១០០។",
    "cinf.note.latest_label": "ទិន្នន័យចុងក្រោយ:",
    "cinf.placeholder": "បញ្ចូលចំនួនទឹកប្រាក់ និងជួរកាលបរិច្ឆេទខាងលើ។",
    "cinf.error.date_order": "ខែ \"ពី\" ត្រូវតែមុនខែ \"ដល់\"។",
    "cinf.result.hero_label": "ថាមពលទិញដែលសមមូល",
    "cinf.result.total_change": "អតិផរណាសរុប",
    "cinf.result.avg_annual": "អត្រាមធ្យមប្រចាំឆ្នាំ",
    "cinf.result.years": "រយៈពេល",
    "cinf.result.cpi_from": "CPI (ពី)",
    "cinf.result.cpi_to": "CPI (ដល់)",
    "cinf.result.interp_label": "ការបកស្រាយ:",
    "cinf.chart.power_title": "ថាមពលទិញតាមពេលវេលា",
    "cinf.chart.yoy_title": "អតិផរណាប្រចាំឆ្នាំ (ធ្នូ YoY %)",
    "cinf.table.title": "ទិន្នន័យ CPI ប្រចាំឆ្នាំ (ខែធ្នូ)",
    "cinf.table.year": "ឆ្នាំ",
    "cinf.table.cpi_index": "សន្ទស្សន៍ CPI (ធ្នូ)",
    "cinf.table.yoy": "ធ្នូ YoY %",
    "cinf.table.cum": "សម្បើមពីឆ្នាំ ២០០៤",
    "cinf.table.source_note": "ប្រភព: NIS កម្ពុជា។ មូលដ្ឋាន CPI តុលា–ធ្នូ ២០០៦ = ១០០។ YoY = ធ្នូ vs. ធ្នូមុន។",
    "cinf.print.note": "គណនាទាំងអស់ប្រើទិន្នន័យ CPI ផ្លូវការរបស់ NIS កម្ពុជា។ សម្រាប់គោលបំណងអប់រំតែប៉ុណ្ណោះ។",
    "cinf.print.btn": "បោះពុម្ព / រក្សាទុក PDF",
    "nssf.page_title": "ម័ស៊ឹនគណនាប្រាក់សោធននិវត្តន៍ NSSF",
    "nssf.page_desc": "ប័ន្ទប់ប្រាក់សោធននិវត្តន៍ប្រចាំខែរបស់អ្នកពីមូលនិធិសន្តិសុខសង្គមជាតិ ដោយផ្អែកលើប្រាក់ខែ និងឆ្នាំរួមចំណែក។",
    "nssf.bread": "សោធននិវត្តន៍ NSSF",
    "nssf.print_title": "ម័ស៊ឹនគណនាប្រាក់សោធននិវត្តន៍ NSSF",
    "nssf.section.personal": "ព័ត៌មានផ្ទាល់ខ្លួន",
    "nssf.section.contribution": "ការរួមចំណែក NSSF",
    "nssf.input.current_age": "អាយុបច្ចុប្បន្ន",
    "nssf.input.retirement_age": "អាយុចូលនិវត្តន៍",
    "nssf.hint.retirement_age": "NSSF កម្ពុជា: អាយុចូលនិវត្តន៍ ៦០ ឆ្នាំ",
    "nssf.input.salary": "ប្រាក់ខែជាមធ្យម",
    "nssf.input.start_date": "ថ្ងៃចាប់ផ្ដើមរួមចំណែក",
    "nssf.hint.start_date": "ថ្ងៃដែលអ្នកចុះឈ្មោះ NSSF ដំបូង",
    "nssf.result.monthly_pension": "ប្រាក់សោធនប្រចាំខែ",
    "nssf.result.annual_pension": "ប្រាក់សោធនប្រចាំឆ្នាំ",
    "nssf.result.total_years": "ឆ្នាំរួមចំណែកសរុប",
    "nssf.result.retirement_year": "ឆ្នាំចូលនិវត្តន៍",
    "nssf.result.pension_rate": "អត្រាសោធន",
    "nssf.result.as_pct_salary": "ប្រាក់សោធនជា % នៃប្រាក់ខែ",
    "nssf.result.formula": "រូបមន្តអត្រា:",
    "nssf.warn.under20": "ការរួមចំណែកតិចជាង ២០ ឆ្នាំ — អ្នកនឹងទទួលបានប្រាក់ជាដុំ ជំនួសឱ្យប្រាក់សោធនប្រចាំខែ។",
    "nssf.warn.zero_years": "ថ្ងៃចាប់ផ្ដើមរួមចំណែក នៅ ឬ ក្រោយការចូលនិវត្តន៍ — គ្មានប្រាក់សោធនបានកើតឡើង។",
    "nssf.chart.title": "ប្រាក់សោធនប្រចាំខែ តាមឆ្នាំរួមចំណែក",
    "nssf.chart.pension": "ប្រាក់សោធនប្រចាំខែ",
    "nssf.chart.you": "ករណីរបស់អ្នក",
    "nssf.table.title": "តារាងគណនាពេញ (ឆ្នាំ ១–៥០)",
    "nssf.table.year": "ឆ្នាំ",
    "nssf.table.formula": "រូបមន្ត",
    "nssf.table.rate": "អត្រា",
    "nssf.table.monthly": "ប្រាក់សោធនប្រចាំខែ",
    "nssf.table.annual": "ប្រាក់សោធនប្រចាំឆ្នាំ",
    "nssf.table.age": "អាយុពេលចូលនិវត្តន៍",
    "nssf.source": "ប្រភព: NSSF កម្ពុជា។ អត្រា: ១.៧៥%/ឆ្នាំ (ឆ្នាំ ១–១៥); ១.២៥%/ឆ្នាំ (ឆ្នាំ ១៦+); អតិបរមា ៧០% នៅ ៥០ ឆ្នាំ។ ត្រូវការ ២០ ឆ្នាំ ដើម្បីបានប្រាក់សោធនប្រចាំខែ។",
    "dp.page_title": "យុត្ថសាស្ត្រសងបំណុល",
    "dti.page_title": "សមាមាត្របំណុលទៅប្រាក់ចំណូល (DTI)",
    "rvb.page_title": "ជួល ឬ ទិញផ្ទះ",
    "hvb.page_title": "សន្សាំ៖ ផ្ទះ ឬ ធនាគារ"
  }
};
